export const MAX_LEVEL = 100;
export type ClassId = "swordsman" | "mage" | "archer";
export type SkillEffect =
  "hit" | "area" | "heal" | "guard" | "fury" | "stun" | "slow" | "poison";
export type Skill = {
  id: string;
  name: string;
  icon: string;
  level: number;
  mp: number;
  cooldown: number;
  range: number;
  power: number;
  effect: SkillEffect;
  radius?: number;
  duration?: number;
  cast?: number;
  description: string;
};
export const classes: Record<
  ClassId,
  {
    name: string;
    role: string;
    icon: string;
    color: number;
    range: number;
    speed: number;
    weapon: string;
  }
> = {
  swordsman: {
    name: "Swordsman",
    role: "Close combat · defense and crowd control",
    icon: "swords",
    color: 0xf29b47,
    range: 1.8,
    speed: 0.7,
    weapon: "Sword",
  },
  mage: {
    name: "Mage",
    role: "Ranged magic · area damage and control",
    icon: "wand-sparkles",
    color: 0xab68ed,
    range: 7,
    speed: 1,
    weapon: "Staff",
  },
  archer: {
    name: "Archer",
    role: "Ranged physical · speed and damage over time",
    icon: "crosshair",
    color: 0x55c68a,
    range: 8,
    speed: 0.8,
    weapon: "Bow",
  },
};
const make = (
  job: ClassId,
  index: number,
  name: string,
  icon: string,
  effect: SkillEffect,
  power: number,
  mp: number,
  cooldown: number,
  description: string,
  extra: Partial<Skill> = {},
): Skill => ({
  id: `${job}-${index}`,
  name,
  icon,
  effect,
  power,
  mp,
  cooldown,
  description,
  level: index * 10,
  range: classes[job].range + 1,
  ...extra,
});
export const skills: Record<ClassId, Skill[]> = {
  swordsman: [
    make(
      "swordsman",
      1,
      "Power Strike",
      "swords",
      "hit",
      1.8,
      10,
      4,
      "A heavy focused strike.",
    ),
    make(
      "swordsman",
      2,
      "Whirlwind",
      "wind",
      "area",
      1.4,
      18,
      7,
      "Sweep every enemy around you.",
      { radius: 4 },
    ),
    make(
      "swordsman",
      3,
      "Iron Guard",
      "shield",
      "guard",
      0.5,
      15,
      15,
      "Reduce incoming damage by 50% for 6 seconds.",
      { duration: 6 },
    ),
    make(
      "swordsman",
      4,
      "Shield Bash",
      "shield",
      "stun",
      1.3,
      16,
      10,
      "Interrupt and stun a target for 2 seconds.",
      { duration: 2 },
    ),
    make(
      "swordsman",
      5,
      "Second Wind",
      "heart",
      "heal",
      0.3,
      20,
      20,
      "Recover 30% of maximum health.",
    ),
    make(
      "swordsman",
      6,
      "War Cry",
      "sparkles",
      "fury",
      0.35,
      24,
      18,
      "Increase attack by 35% for 8 seconds.",
      { duration: 8 },
    ),
    make(
      "swordsman",
      7,
      "Cleave",
      "swords",
      "area",
      2.2,
      28,
      10,
      "A powerful sweep around your target.",
      { radius: 3 },
    ),
    make(
      "swordsman",
      8,
      "Hamstring",
      "wind",
      "slow",
      2,
      25,
      12,
      "Slow a target for 5 seconds.",
      { duration: 5 },
    ),
    make(
      "swordsman",
      9,
      "Earthbreaker",
      "anvil",
      "area",
      3,
      35,
      15,
      "Shake the ground around you.",
      { radius: 5 },
    ),
    make(
      "swordsman",
      10,
      "Meteor Blade",
      "sparkles",
      "area",
      4.5,
      50,
      25,
      "Unleash your strongest sweeping attack.",
      { radius: 5, cast: 0.6 },
    ),
  ],
  mage: [
    make(
      "mage",
      1,
      "Fire Bolt",
      "sparkles",
      "hit",
      2,
      12,
      4,
      "Launch a burning bolt.",
      { cast: 0.35 },
    ),
    make(
      "mage",
      2,
      "Frost Nova",
      "wind",
      "area",
      1.5,
      20,
      8,
      "Burst around the target and slow nearby enemies.",
      { radius: 3, duration: 3, cast: 0.4 },
    ),
    make(
      "mage",
      3,
      "Arcane Barrier",
      "shield",
      "guard",
      0.6,
      18,
      16,
      "Reduce incoming damage by 60% for 5 seconds.",
      { duration: 5 },
    ),
    make(
      "mage",
      4,
      "Lightning",
      "sparkles",
      "stun",
      1.6,
      22,
      10,
      "Stun a target for 2 seconds.",
      { duration: 2, cast: 0.3 },
    ),
    make(
      "mage",
      5,
      "Vital Bloom",
      "heart",
      "heal",
      0.35,
      25,
      20,
      "Recover 35% of maximum health.",
    ),
    make(
      "mage",
      6,
      "Arcane Focus",
      "wand-sparkles",
      "fury",
      0.4,
      25,
      18,
      "Increase attack by 40% for 8 seconds.",
      { duration: 8 },
    ),
    make(
      "mage",
      7,
      "Blizzard",
      "wind",
      "area",
      2.5,
      35,
      12,
      "Freeze the air around your target.",
      { radius: 4, duration: 4, cast: 0.7 },
    ),
    make(
      "mage",
      8,
      "Venom Cloud",
      "flask-conical",
      "poison",
      1.2,
      30,
      14,
      "A poisonous spell that damages over 6 seconds.",
      { duration: 6 },
    ),
    make(
      "mage",
      9,
      "Starfall",
      "sparkles",
      "area",
      3.4,
      42,
      18,
      "Call falling stars onto a wide area.",
      { radius: 5, cast: 0.8 },
    ),
    make(
      "mage",
      10,
      "Astral Storm",
      "wand-sparkles",
      "area",
      5,
      60,
      28,
      "A devastating arcane storm.",
      { radius: 6, cast: 1 },
    ),
  ],
  archer: [
    make(
      "archer",
      1,
      "Power Shot",
      "crosshair",
      "hit",
      1.9,
      10,
      4,
      "A precise, powerful arrow.",
    ),
    make(
      "archer",
      2,
      "Arrow Rain",
      "wind",
      "area",
      1.5,
      18,
      8,
      "Rain arrows around your target.",
      { radius: 3 },
    ),
    make(
      "archer",
      3,
      "Evasive Stance",
      "shield",
      "guard",
      0.45,
      15,
      14,
      "Reduce incoming damage by 45% for 6 seconds.",
      { duration: 6 },
    ),
    make(
      "archer",
      4,
      "Pinning Shot",
      "crosshair",
      "stun",
      1.4,
      18,
      10,
      "Pin a target for 2 seconds.",
      { duration: 2 },
    ),
    make(
      "archer",
      5,
      "Field Remedy",
      "heart",
      "heal",
      0.25,
      18,
      18,
      "Recover 25% of maximum health.",
    ),
    make(
      "archer",
      6,
      "Hunter Focus",
      "crosshair",
      "fury",
      0.3,
      22,
      16,
      "Increase attack by 30% for 10 seconds.",
      { duration: 10 },
    ),
    make(
      "archer",
      7,
      "Piercing Volley",
      "swords",
      "area",
      2.2,
      28,
      10,
      "Piercing arrows strike nearby enemies.",
      { radius: 3.5 },
    ),
    make(
      "archer",
      8,
      "Poison Arrow",
      "flask-conical",
      "poison",
      1.1,
      24,
      12,
      "Poison a target for 8 seconds.",
      { duration: 8 },
    ),
    make(
      "archer",
      9,
      "Crippling Shot",
      "wind",
      "slow",
      3,
      32,
      14,
      "A heavy arrow that slows for 6 seconds.",
      { duration: 6 },
    ),
    make(
      "archer",
      10,
      "Sky Barrage",
      "sparkles",
      "area",
      4.5,
      48,
      24,
      "Cover the target area in a storm of arrows.",
      { radius: 5, cast: 0.5 },
    ),
  ],
};
export function isClass(value: unknown): value is ClassId {
  return typeof value === "string" && Object.hasOwn(classes, value);
}
/** Base mitigation formula; variability and critical hits are applied before this step. */
export function damageAfterDefense(atk: number, def: number) {
  return (Math.max(0, atk) * 100) / (100 + Math.max(0, def));
}
