import {test,expect} from '@playwright/test';
import {mkdirSync} from 'node:fs';
import {gearById,secondaryRollMaximum,type SecondaryStat} from '../src/game/equipment';
test('admin switch grants maximum affixes, persists while reopening and stays hidden for materials',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('mossvale-quality','low'));
 await page.goto('/');await page.locator('#account-register').click();await page.locator('#account-username').fill('maxqa_'+Date.now());await page.locator('#account-password').fill('Max roll QA password 123!');await page.locator('#account-confirm').fill('Max roll QA password 123!');await page.locator('#account-login').click();await page.locator('#character-name').fill('Maximum Hero');await page.getByRole('button',{name:'Create character',exact:true}).click();await page.locator('#character-start').click();await expect(page.locator('#hp-text')).toContainText('/',{timeout:90000});await page.waitForFunction(()=>{const s=(window as any).mossvale?.snapshot();return s&&s.modelsExpected>0&&s.riggedActors===s.modelsExpected&&s.modelErrors===0},null,{timeout:90000});
 await page.locator('[data-panel="settings"]').first().click();await page.locator('[data-panel="admin"]').click();
 const choose=async(label:string,name:string)=>{await page.getByRole('combobox',{name:label,exact:true}).click();await page.getByRole('option',{name,exact:true}).click()};
 await choose('Category','Weapons');const toggle=page.getByRole('switch',{name:'Max secondary rolls'});await expect(toggle).not.toBeChecked();await toggle.check();expect((await toggle.boundingBox())!.width).toBe(48);await expect(toggle).toHaveCSS('background-color','rgb(102, 126, 60)');await choose('Rarity','Legend');
 const id=await page.locator('#spawn-item').inputValue();await page.getByRole('button',{name:'Spawn into my bag'}).click();
 await expect.poll(()=>page.evaluate(id=>(window as any).mossvale.snapshot().items.filter((i:any)=>i.gearId===id&&i.rarity==='legend').length,id)).toBe(1);
 const item=await page.evaluate(id=>(window as any).mossvale.snapshot().items.find((i:any)=>i.gearId===id&&i.rarity==='legend'),id);const gear=gearById(id)!;expect(Object.keys(item.secondary)).toHaveLength(5);for(const [key,value] of Object.entries(item.secondary))expect(value).toBe(secondaryRollMaximum(key as SecondaryStat,gear.level));await expect(toggle).toBeChecked();
 mkdirSync('artifacts/admin-max-roll',{recursive:true});await page.screenshot({path:'artifacts/admin-max-roll/desktop.png'});await page.locator('#close-panel').click();await page.locator('[data-panel="settings"]').first().click();await page.locator('[data-panel="admin"]').click();await expect(toggle).toBeChecked();await choose('Category','Materials');await expect(toggle).toBeHidden();await choose('Category','Weapons');await expect(toggle).toBeChecked();await toggle.uncheck();await expect(toggle).not.toBeChecked();expect(errors).toEqual([]);
});
