import {test,expect} from '@playwright/test';
import {Simulation} from '../src/simulation';
import {gearById,rollGear} from '../src/game/equipment';
import {mkdirSync} from 'node:fs';
test.use({hasTouch:true});
async function load(page:any){const sim=new Simulation(()=>.5,undefined,null);sim.save.level=30;sim.chooseSkill('swordsman-1');sim.chooseSkill('swordsman-2');sim.save.hp=sim.maxHp;sim.save.mp=sim.maxMp;const gear=gearById('thornwood-weapon')!;sim.addEquipmentItem({...rollGear(gear.id,'rare',()=>.5),name:gear.name,icon:gear.icon,count:1});await page.addInitScript((save:any)=>{localStorage.setItem('mossvale-save',JSON.stringify(save));localStorage.setItem('mossvale-quality','low')},sim.save);await page.goto('/?practice=1');await page.locator('#practice-start').click();await expect(page.locator('#level-badge')).toHaveText('30');await expect(page.locator('#hp-text')).toContainText('/');await page.waitForFunction(()=>{const s=(window as any).mossvale?.snapshot();return s&&s.modelsExpected>0&&s.modelErrors===0&&s.riggedActors===s.modelsExpected},{},{timeout:60000});}
test('portrait and landscape keep all combat controls inside two thumb areas and menus collapsed',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:390,height:844});await load(page);mkdirSync('artifacts/compact-hud',{recursive:true});
 for(const viewport of [{width:390,height:844},{width:844,height:390},{width:568,height:320}]){await page.setViewportSize(viewport);await expect(page.locator('#mobile-menu')).toBeHidden();await expect(page.locator('.quest-tracker')).toBeHidden();await expect(page.locator('.side-menu')).toBeHidden();await expect(page.locator('.chat')).toBeHidden();
  const boxes=await page.locator('#mobile-joystick,#mobile-attack,#mobile-auto,#mobile-loot,.skill-hotbar [data-skill],.aux-hotbar [data-aux]').evaluateAll(nodes=>nodes.map(n=>{const b=n.getBoundingClientRect();return{id:n.id,x:b.x,y:b.y,w:b.width,h:b.height}}));expect(boxes).toHaveLength(14);for(const b of boxes){expect(b.x).toBeGreaterThanOrEqual(0);expect(b.y).toBeGreaterThanOrEqual(0);expect(b.x+b.w).toBeLessThanOrEqual(viewport.width+1);expect(b.y+b.h).toBeLessThanOrEqual(viewport.height+1);expect(b.w).toBeGreaterThanOrEqual(44);expect(b.h).toBeGreaterThanOrEqual(44)}const joystick=boxes.find(b=>b.id==='mobile-joystick')!;expect(joystick.x+joystick.w).toBeLessThan(viewport.width/2);for(const id of ['mobile-attack','mobile-auto','mobile-loot'])expect(boxes.find(b=>b.id===id)!.x).toBeGreaterThan(viewport.width/2);
  const menuBounds=(await page.locator('#mobile-menu-toggle').boundingBox())!,mapBounds=(await page.locator('.map-area').boundingBox())!;expect(menuBounds.x<mapBounds.x+mapBounds.width&&menuBounds.x+menuBounds.width>mapBounds.x&&menuBounds.y<mapBounds.y+mapBounds.height&&menuBounds.y+menuBounds.height>mapBounds.y).toBe(false);
  await page.screenshot({path:`artifacts/compact-hud/default-${viewport.width}.png`});
  await page.locator('#mobile-menu-toggle').tap();await expect(page.locator('#mobile-menu-toggle')).toHaveAttribute('aria-expanded','true');for(const panel of ['inventory','skills','character','forge','shop','journal','map','community','market','settings','help'])await expect(page.locator(`#mobile-menu [data-mobile-panel="${panel}"]`)).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#mobile-menu')).toBeHidden();
 }
 await page.setViewportSize({width:390,height:844});const beforeAttack=await page.evaluate(()=>(window as any).mossvale.snapshot());await page.locator('#mobile-attack').tap();await page.waitForFunction(kills=>{const s=(window as any).mossvale.snapshot();return s.target!==null||s.kills>kills},beforeAttack.kills);const selected=await page.evaluate(()=>(window as any).mossvale.snapshot());const normalAttack={kills:beforeAttack.kills,target:selected.target,hp:beforeAttack.monsters.find((m:any)=>m.id===selected.target)?.hp};await page.waitForFunction(before=>{const s=(window as any).mossvale.snapshot();return s.kills>before.kills||s.monsters.some((m:any)=>m.id===before.target&&m.hp<before.hp)},normalAttack,{timeout:20000});const beforeAutoMp=await page.evaluate(()=>(window as any).mossvale.snapshot().mp);await page.locator('#mobile-auto').tap();await expect(page.locator('#mobile-auto')).toHaveAttribute('aria-pressed','true');await page.waitForFunction(before=>{const s=(window as any).mossvale.snapshot();return s.mp<before&&Object.values(s.skillCooldowns).some((n:any)=>n>0)},beforeAutoMp,{timeout:20000});await page.locator('#mobile-auto').tap();expect(errors).toEqual([]);
});
test('bag categories form one icon row, paired equipment order and filtering preserve item ownership',async({page})=>{
 await page.setViewportSize({width:390,height:844});await load(page);const before=await page.evaluate(()=>(window as any).mossvale.snapshot());await page.locator('#mobile-menu-toggle').tap();await page.locator('#mobile-menu [data-mobile-panel="inventory"]').tap();await expect(page.locator('#mobile-menu')).toBeHidden();
 await expect(page.locator('#mobile-menu-toggle')).toBeHidden();
 for(const width of [390,320,360]){await page.setViewportSize({width,height:width===320?568:844});
  const geometry=await page.locator('[data-bag-category]').evaluateAll(nodes=>nodes.map(n=>{const b=n.getBoundingClientRect();return{top:b.top,left:b.left,right:b.right,height:b.height}}));expect(new Set(geometry.map(b=>Math.round(b.top))).size).toBe(1);for(const b of geometry){expect(b.left).toBeGreaterThanOrEqual(0);expect(b.right).toBeLessThanOrEqual(width);expect(b.height).toBeGreaterThanOrEqual(44)}
  expect(await page.locator('#close-panel').evaluate(element=>{const b=element.getBoundingClientRect();return document.elementFromPoint(b.left+b.width/2,b.top+b.height/2)?.closest('#close-panel')===element})).toBe(true);
 }
 await page.setViewportSize({width:390,height:844});
 await expect(page.locator('[data-bag-category]')).toHaveCount(7);const tabs=await page.locator('[data-bag-category]').evaluateAll(nodes=>nodes.map(n=>({top:n.getBoundingClientRect().top,text:n.textContent?.trim(),label:n.getAttribute('aria-label')})));expect(new Set(tabs.map(n=>Math.round(n.top))).size).toBe(1);expect(tabs.every(n=>n.text===''&&n.label)).toBe(true);expect(await page.locator('[data-worn-slot]').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('data-worn-slot')))).toEqual(['weapon','accessory','helmet','armor','pants','boots']);
 await page.getByRole('tab',{name:'Weapons',exact:true}).tap();await expect(page.getByRole('tab',{name:'Weapons',exact:true})).toHaveAttribute('aria-selected','true');await page.keyboard.press('ArrowRight');await expect(page.getByRole('tab',{name:'Armor',exact:true})).toHaveAttribute('aria-selected','true');const after=await page.evaluate(()=>(window as any).mossvale.snapshot());expect(after.items).toEqual(before.items);expect(after.equipped).toEqual(before.equipped);mkdirSync('artifacts/compact-hud',{recursive:true});await page.screenshot({path:'artifacts/compact-hud/bag-portrait.png'});
 await page.setViewportSize({width:1200,height:800});await expect(page.locator('[data-bag-category]')).toHaveCount(7);await page.screenshot({path:'artifacts/compact-hud/bag-desktop.png'});
});

test('mobile Quests keeps the starter reward reachable and grants it only once',async({page})=>{
 await page.setViewportSize({width:390,height:844});const sim=new Simulation(()=>.5,undefined,null);sim.save.kills=5;sim.save.questClaimed=false;const gold=sim.save.gold,red=sim.save.items.find(i=>i.name==='Red potion')!.count;
 await page.addInitScript(save=>{localStorage.setItem('mossvale-save',JSON.stringify(save));localStorage.setItem('mossvale-quality','low')},sim.save);await page.goto('/?practice=1');await page.locator('#practice-start').click();await expect(page.locator('#hp-text')).toContainText('/');await page.waitForFunction(()=>{const s=(window as any).mossvale?.snapshot();return s&&s.modelsExpected>0&&s.modelErrors===0&&s.riggedActors===s.modelsExpected},{},{timeout:60000});
 await page.locator('#mobile-menu-toggle').tap();await page.locator('#mobile-menu [data-mobile-panel="journal"]').tap();const claim=page.locator('[data-claim-beginner]');await expect(claim).toBeEnabled();await claim.tap();await expect(claim).toBeDisabled();await expect(claim).toHaveText('Completed');
 const claimed=await page.evaluate(()=>(window as any).mossvale.snapshot());expect(claimed.gold).toBe(gold+100);expect(claimed.items.find((i:any)=>i.name==='Red potion').count).toBe(red+3);
 await page.locator('#close-panel').tap();await page.locator('#mobile-menu-toggle').tap();await page.locator('#mobile-menu [data-mobile-panel="journal"]').tap();await expect(claim).toBeDisabled();await claim.evaluate((button:HTMLButtonElement)=>button.click());const repeated=await page.evaluate(()=>(window as any).mossvale.snapshot());expect(repeated.gold).toBe(claimed.gold);expect(repeated.items).toEqual(claimed.items);
});
