import {test,expect} from '@playwright/test';
import {Simulation} from '../src/simulation';
const seed=()=>{const sim=new Simulation(()=>.5,undefined,null);sim.save.level=100;sim.save.version=6;sim.addItem('Frost Edge','frostguard-blade');const weapon=sim.save.items.find(i=>i.gearId==='frost-edge')!;weapon.refine=10;sim.equip(weapon.id!);return sim.save};
test('1200×800 HUD clusters fit, do not overlap, and equipment shows exact refinement bonus',async({page})=>{
 await page.setViewportSize({width:1200,height:800});const save=seed();await page.addInitScript(save=>{localStorage.setItem('mossvale-save',JSON.stringify(save));localStorage.setItem('mossvale-quality','low')},save);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?practice=1');await page.locator('#practice-start').click();await expect(page.locator('#hp-text')).toContainText('/');
 const bounds=await page.evaluate(()=>['.identity','.map-area','.quest-tracker','.side-menu','.chat','.bottom-center','.bottom-right','.world-heading'].map(selector=>{const r=document.querySelector(selector)!.getBoundingClientRect();return {selector,x:r.x,y:r.y,right:r.right,bottom:r.bottom}}));
 for(const a of bounds){expect(a.x,a.selector).toBeGreaterThanOrEqual(0);expect(a.y,a.selector).toBeGreaterThanOrEqual(0);expect(a.right,a.selector).toBeLessThanOrEqual(1200);expect(a.bottom,a.selector).toBeLessThanOrEqual(800);for(const b of bounds){if(a.selector===b.selector)continue;expect(Math.min(a.right,b.right)-Math.max(a.x,b.x)>1&&Math.min(a.bottom,b.bottom)-Math.max(a.y,b.y)>1,a.selector+' overlaps '+b.selector).toBe(false);}}
 await page.screenshot({path:'artifacts/hud-1200x800.png'});await page.keyboard.press('i');await expect(page.locator('.inventory-grid > .item')).toHaveCount(48);await page.locator('.inventory-grid [data-item="'+save.equipped.weapon+'"]').hover();await expect(page.getByRole('tooltip')).toContainText('245 (+145)');await page.screenshot({path:'artifacts/bonus-1200x800.png'});await page.mouse.move(0,0);
 for(const panel of ['inventory','character','skills','forge','shop','map','settings','help','journal']){await page.keyboard.press('Escape');await page.locator('[data-panel="'+panel+'"]').first().count().then(async count=>{if(count)await page.locator('[data-panel="'+panel+'"]').first().click();else if(panel==='journal')await page.keyboard.press('j');});const dialog=page.getByRole('dialog');if(await dialog.count()){const box=(await dialog.boundingBox())!;expect(box.x).toBeGreaterThanOrEqual(0);expect(box.y).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(1200);expect(box.y+box.height).toBeLessThanOrEqual(800);expect(await page.locator('select:visible').count()).toBe(0);}}
 expect(errors).toEqual([]);
});
test('custom dropdown supports keyboard, Escape, pointer and scrolling without native popups',async({page})=>{
 await page.setViewportSize({width:1200,height:800});await page.addInitScript(save=>{localStorage.setItem('mossvale-save',JSON.stringify(save));localStorage.setItem('mossvale-quality','low')},seed());await page.goto('/?practice=1');await page.locator('#practice-start').click();await expect(page.locator('#hp-text')).toContainText('/');await page.locator('[data-panel="settings"]').click();const quality=page.getByRole('combobox',{name:'Graphics quality'});await quality.click();await expect(page.getByRole('listbox')).toBeVisible();await page.screenshot({path:'artifacts/custom-dropdown-1200x800.png'});await page.keyboard.press('Home');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await expect(page.locator('#graphics-quality')).toHaveValue('high');await expect(quality).toHaveText('high');await quality.click();await page.keyboard.press('Escape');await expect(page.getByRole('listbox')).toHaveCount(0);await expect(page.getByRole('dialog')).toBeVisible();await quality.click();await page.getByRole('option',{name:'low',exact:true}).click();await expect(page.locator('#graphics-quality')).toHaveValue('low');
 await page.keyboard.press('Escape');await page.keyboard.press('k');const slot=page.getByRole('combobox',{name:'Hotbar slot for Power Strike'});await slot.click();await page.getByRole('option',{name:'Key 3',exact:true}).click();await page.locator('[data-assign="swordsman-1"]').click();await expect(page.locator('.loadout-slot[data-hotbar="2"]')).toContainText('Power Strike');
 await page.setViewportSize({width:390,height:844});await page.keyboard.press('Escape');await page.locator('[data-panel="settings"]').click();await page.getByRole('combobox',{name:'Graphics quality'}).click();const box=(await page.getByRole('listbox').boundingBox())!;expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(390);expect(box.y+box.height).toBeLessThanOrEqual(844);await page.screenshot({path:'artifacts/custom-dropdown-mobile.png'});
});
test('admin dropdowns update dependent item choices and still grant items on the server',async({page})=>{
 await page.setViewportSize({width:1200,height:800});await page.addInitScript(()=>localStorage.setItem('mossvale-quality','low'));await page.goto('/?online=1');await expect(page.locator('#hp-text')).toContainText('/');await page.locator('[data-panel="settings"]').click();await page.locator('[data-panel="admin"]').click();await page.locator('#spawn-category-trigger').click();await page.getByRole('option',{name:'Refine stones',exact:true}).click();await page.locator('#spawn-item-trigger').click();await page.getByRole('option',{name:'Rare refine stone',exact:true}).click();await expect(page.locator('#spawn-preview')).toContainText('Rare refine stone');await expect(page.locator('#spawn-equipment')).toBeHidden();const before=await page.evaluate(()=>(window as any).mossvale.snapshot().items.find((i:any)=>i.name==='Rare refine stone')?.count||0);await page.getByRole('button',{name:'Spawn into my bag'}).click();await expect.poll(()=>page.evaluate(()=>(window as any).mossvale.snapshot().items.find((i:any)=>i.name==='Rare refine stone')?.count||0)).toBe(before+1);await page.screenshot({path:'artifacts/admin-custom-1200x800.png'});await page.keyboard.press('Escape');await page.locator('[data-panel="settings"]').click();await page.locator('#realm-tools').click();await expect(page.locator('#operations-report')).not.toContainText('Loading realm report');await page.locator('#backup-realm').click();await expect(page.locator('#restore-backup-trigger')).not.toContainText('Loading');await page.locator('#restore-backup-trigger').click();await expect(page.getByRole('option').first()).toContainText('revision');await page.keyboard.press('Escape');
});
