import {test,expect} from '@playwright/test';import {mkdirSync} from 'node:fs';
test('mobile admin item dropdown scrolls with real touch gestures without selecting, then a tap selects',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});try{const page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('mossvale-quality','low'));
 await page.goto('/');const username=process.env.DROPDOWN_QA_USERNAME; if(!username)await page.locator('#account-register').tap();await page.locator('#account-username').fill(username||('touchqa_'+Date.now()));await page.locator('#account-password').fill('Touch QA password 123!');if(!username)await page.locator('#account-confirm').fill('Touch QA password 123!');await page.locator('#account-login').tap();if(!username){await page.locator('#character-name').fill('Touch Tester');await page.getByRole('button',{name:'Create character',exact:true}).tap()}await page.locator('#character-start').tap();await expect(page.locator('#hp-text')).toContainText('/',{timeout:90000});await page.waitForFunction(()=>{const s=(window as any).mossvale?.snapshot();return s&&s.modelsExpected>0&&s.riggedActors===s.modelsExpected&&s.modelErrors===0},null,{timeout:90000});
 await page.locator('#mobile-menu-toggle').tap();await page.locator('[data-mobile-panel="settings"]').tap();await page.locator('[data-panel="admin"]').tap();await page.getByRole('combobox',{name:'Category',exact:true}).tap();await page.getByRole('option',{name:'Armor',exact:true}).tap();await page.waitForTimeout(700);const select=page.locator('#spawn-item'),initial=await select.inputValue();await page.evaluate(()=>{(window as any).__itemChanges=0;document.querySelector('#spawn-item')!.addEventListener('change',()=>{(window as any).__itemChanges++})});await page.getByRole('combobox',{name:'Item',exact:true}).tap();const list=page.getByRole('listbox',{name:'Item',exact:true});await expect(list).toBeVisible();const r=(await list.boundingBox())!,x=r.x+r.width/2,start=r.y+r.height-24,end=r.y+24;
 const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y:start}]});await expect(list).toBeVisible();expect(await select.inputValue()).toBe(initial);
 for(let step=1;step<=10;step++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:start+(end-start)*step/10}]});await page.waitForTimeout(35)}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect.poll(()=>list.evaluate(e=>e.scrollTop)).toBeGreaterThan(40);await expect(list).toBeVisible();expect(await select.inputValue()).toBe(initial);expect(await page.evaluate(()=>(window as any).__itemChanges)).toBe(0);
 // Wait for native momentum to settle before tapping an option.
 await page.waitForTimeout(1000);const top=await list.evaluate(e=>e.scrollTop),beforeBox=(await list.boundingBox())!;const rows=await list.getByRole('option').all();let target=rows[0];for(const row of rows){const box=await row.boundingBox();if(box&&box.y>beforeBox.y+12&&box.y+box.height<beforeBox.y+beforeBox.height-12){target=row;break}}const value=await target.getAttribute('data-value');expect(value).not.toBe(initial);mkdirSync('artifacts/dropdown-touch',{recursive:true});await page.screenshot({path:'artifacts/dropdown-touch/mobile-scrolled.png'});await target.tap();await expect(list).toHaveCount(0);await expect(select).toHaveValue(value!);expect(await page.evaluate(()=>(window as any).__itemChanges)).toBe(1);expect(top).toBeGreaterThan(40);expect(errors).toEqual([]);
 }finally{await context.close()}
});
test('mouse selection and keyboard End/Enter still choose options',async({page})=>{
 await page.goto('/?practice=1');await page.evaluate(async()=>{const {enhanceGameSelects}=await import('/src/ui/game-select.ts');const root=document.createElement('div');root.style.cssText='position:fixed;top:80px;left:40px;z-index:999';root.innerHTML='<label>Fixture<select id="fixture">'+Array.from({length:30},(_,i)=>'<option value="'+i+'">Option '+i+'</option>').join('')+'</select></label>';document.body.append(root);enhanceGameSelects(root)});const button=page.getByRole('combobox',{name:'Fixture',exact:true});await button.click();await page.getByRole('option',{name:'Option 4',exact:true}).click();await expect(page.locator('#fixture')).toHaveValue('4');await button.press('ArrowDown');await button.press('End');await button.press('Enter');await expect(page.locator('#fixture')).toHaveValue('29');await expect(page.getByRole('listbox')).toHaveCount(0);
});
