import {test,expect} from '@playwright/test';
import {writeFileSync} from 'node:fs';
test('Archer stage 10 visible crossbow and feet frozen and live landing bounds',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/ground-review.html*',r=>r.fulfill({contentType:'text/html',body:'<body style="margin:0"><canvas style="width:100vw;height:100vh"></canvas><div id="label" style="position:absolute;top:0"></div><script type="module" src="/tests/dynamic-skills-fixture.ts"></script>'}));await page.goto('/ground-review.html?job=archer');await page.waitForFunction(()=>(window as any).review?.library.active===1,{},{timeout:45000});
 await page.evaluate(()=>{const r=(window as any).review;r.camera.position=new r.Vector3(5,.65,6);r.camera.setTarget(new r.Vector3(0,.65,0));});const freshIdle=await page.evaluate(()=>(window as any).review.describe());await page.screenshot({path:'artifacts/dynamic-skills/ground-fresh-idle.png'});const records:any[]=[];const points=[.68,.72,.76,.8,.84,.9,1];for(const id of ['archer-10','archer-b-10']){
 for(const p of points){await page.evaluate(({id,p})=>(window as any).review.preview(id,p),{id,p});const d=await page.evaluate(()=>(window as any).review.describe());records.push({id,mode:'frozen',requestedProgress:p,...d});await page.screenshot({path:`artifacts/dynamic-skills/ground-${id}-frozen-${p}.png`});}
 const live=await page.evaluate(async({id,points})=>{const r=(window as any).review;r.play(id);const samples:any[]=[];let started=false,index=0;const deadline=performance.now()+10000;while(index<points.length&&performance.now()<deadline){await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));const d=r.describe(),c=d.poses[0]?.context;started ||= c?.skillId===id&&c.frozen===false;if(!started)continue;if(c?.frozen)continue;while(index<points.length&&((c?.progress??1)>=points[index]))samples.push({id,mode:'live',requestedProgress:points[index++],...d});}return samples;},{id,points});expect(live.length).toBe(points.length);records.push(...live);await page.screenshot({path:`artifacts/dynamic-skills/ground-${id}-post-idle.png`});
 }
 writeFileSync('artifacts/dynamic-skills/archer-grounding-final.json',JSON.stringify({freshIdle,records,errors},null,2));expect(errors).toEqual([]);for(const d of records){const weapon=d.bodyBounds.filter((b:any)=>/2H_Crossbow/.test(b.name));expect(weapon.length,'visible actual crossbow').toBeGreaterThan(0);expect(Math.min(...weapon.map((b:any)=>b.minY)),`${d.id} ${d.mode} requested ${d.requestedProgress} actual ${d.poses[0]?.context.progress??'idle'} weapon`).toBeGreaterThanOrEqual(-.05);expect(d.bodyMinY,`${d.id} ${d.mode} ${d.requestedProgress} visible feet/body`).toBeGreaterThanOrEqual(-.05);}
});
test('fresh Archer idle baseline over one second',async({page})=>{
 await page.route('**/idle-review.html*',r=>r.fulfill({contentType:'text/html',body:'<body style="margin:0"><canvas style="width:100vw;height:100vh"></canvas><div id="label"></div><script type="module" src="/tests/dynamic-skills-fixture.ts"></script>'}));await page.goto('/idle-review.html?job=archer');await page.waitForFunction(()=>(window as any).review?.library.active===1,{},{timeout:45000});await page.evaluate(()=>{const r=(window as any).review;r.camera.position=new r.Vector3(5,.65,6);r.camera.setTarget(new r.Vector3(0,.65,0));});const initial=await page.evaluate(()=>(window as any).review.describe());await page.waitForTimeout(1000);const oneSecond=await page.evaluate(()=>(window as any).review.describe());await page.screenshot({path:'artifacts/dynamic-skills/ground-fresh-idle-one-second.png'});writeFileSync('artifacts/dynamic-skills/archer-idle-baseline.json',JSON.stringify({initial,oneSecond},null,2));
});
test('Archer run and basic attack return to safe idle without persistent blending override',async({page})=>{
 await page.route('**/transitions-review.html*',r=>r.fulfill({contentType:'text/html',body:'<canvas style="width:100vw;height:100vh"></canvas><div id="label"></div><script type="module" src="/tests/dynamic-skills-fixture.ts"></script>'}));await page.goto('/transitions-review.html?job=archer');await page.waitForFunction(()=>(window as any).review?.library.active===1,{},{timeout:45000});
 const records:any[]=[];for(const motion of ['run','attack']){await page.evaluate(motion=>{const r=(window as any).review;r.library.animate(r.actor,motion==='run',120,motion==='attack',false,.016);},motion);await page.waitForTimeout(300);records.push({motion,...await page.evaluate(()=>(window as any).review.describe())});await page.evaluate(()=>{const r=(window as any).review;r.library.animate(r.actor,false,120,false,false,1);});await page.waitForTimeout(300);const d=await page.evaluate(()=>(window as any).review.describe());records.push({motion:motion+'-idle',...d});expect(d.bodyMinY).toBeGreaterThanOrEqual(-.05);}
 writeFileSync('artifacts/dynamic-skills/archer-safe-idle-transitions.json',JSON.stringify({records},null,2));await page.screenshot({path:'artifacts/dynamic-skills/ground-archer-after-basic-attack.png'});
});
