import {test,expect} from '@playwright/test';
import {writeFileSync,mkdirSync} from 'node:fs';
import {Simulation} from '../src/simulation';
import {skills} from '../src/game/classes';
const out='artifacts/dynamic-skills';
async function setup(page:any){
 mkdirSync(out,{recursive:true});const sim=new Simulation(()=>.5,undefined,null);sim.save.job='mage';sim.save.level=100;sim.save.hp=sim.maxHp;sim.save.mp=sim.maxMp;for(let n=1;n<=10;n++)sim.chooseSkill(`mage-${n}`);sim.assignSkill(0,'mage-10');
 await page.addInitScript(save=>{localStorage.setItem('mossvale-save',JSON.stringify(save));localStorage.setItem('mossvale-quality','low')},sim.save);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?practice=1');await page.waitForFunction(()=>{const s=(window as any).mossvale?.snapshot();return s&&s.drawCalls>0&&s.riggedActors>=s.monsters.length+3},{},{timeout:45000});expect(errors).toEqual([]);
}
test('software renderer idle/burst timing and 60 skill sustained pool',async({page})=>{
 await setup(page);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const measure=()=>page.evaluate(async()=>{const dt:number[]=[],samples:any[]=[];let previous=performance.now();for(let n=0;n<30;n++){await new Promise<void>(r=>requestAnimationFrame(()=>r()));const now=performance.now();dt.push(now-previous);previous=now;samples.push((window as any).mossvale.snapshot());}dt.sort((a,b)=>a-b);const calls=samples.map(s=>s.drawCalls);return {frames:dt.length,frameP50:dt[Math.floor(dt.length*.5)],frameP95:dt[Math.ceil(dt.length*.95)-1],meanFps:1000/(dt.reduce((a,b)=>a+b,0)/dt.length),drawCallsMin:Math.min(...calls),drawCallsMax:Math.max(...calls),sceneMeshesMax:Math.max(...samples.map(s=>s.sceneMeshes)),activeVfxMax:Math.max(...samples.map(s=>s.vfx.active)),poolMax:Math.max(...samples.map(s=>s.vfx.pooled)),materialsMax:Math.max(...samples.map(s=>s.vfx.materials)),modelErrorsMax:Math.max(...samples.map(s=>s.modelErrors))};});
 const results:any[]=[];for(const quality of ['low','high']){await page.locator('[data-panel="settings"]').click();await page.getByRole('combobox',{name:'Graphics quality'}).click({timeout:20000});await page.getByRole('option',{name:quality,exact:true}).click({timeout:20000});await expect(page.locator('#graphics-quality')).toHaveValue(quality);await page.keyboard.press('Escape');await page.waitForTimeout(250);const idle=await measure();await page.evaluate(()=>{(window as any).mossvale.previewSkill('mage-10',.15)});const burst=await measure();expect(burst.activeVfxMax).toBeGreaterThan(0);expect(burst.poolMax).toBeLessThanOrEqual(160);expect(burst.materialsMax).toBeLessThanOrEqual(64);expect(burst.modelErrorsMax).toBe(0);await page.evaluate(()=>(window as any).mossvale.clearSkillPreview());results.push({quality,idle,burst});writeFileSync(`${out}/performance-measurement-final.json`,JSON.stringify({environment:'Headless Chromium ANGLE SwiftShader software renderer; not player hardware FPS',results,errors},null,2));console.log('QA_MEASURED',quality);}
 const sustained:any[]=[];for(const job of ['swordsman','archer','mage'] as const){await page.keyboard.press('c');await page.locator(`[data-class="${job}"]`).click();await page.keyboard.press('Escape');await page.waitForFunction(job=>(window as any).mossvale.snapshot().job===job,job,{timeout:10000});const batch=await page.evaluate(ids=>{const records:any[]=[];const m=(window as any).mossvale;for(let repeat=0;repeat<3;repeat++)for(const id of ids){const before=m.snapshot();m.previewSkill(id,.3);const d=m.snapshot();m.clearSkillPreview();records.push({repeat,id,gameplayUnchanged:before.x===d.x&&before.z===d.z&&before.hp===d.hp&&before.mp===d.mp&&before.kills===d.kills&&JSON.stringify(before.skillCooldowns)===JSON.stringify(d.skillCooldowns),vfx:d.vfx,sceneMeshes:d.sceneMeshes,modelErrors:d.modelErrors});}return records;},skills[job].map(s=>s.id));for(const d of batch){expect(d.gameplayUnchanged).toBe(true);expect(d.vfx.pooled).toBeLessThanOrEqual(160);expect(d.modelErrors).toBe(0);sustained.push(d);}writeFileSync(`${out}/performance-pools-final.json`,JSON.stringify({sustained,errors},null,2));console.log('QA_POOLED',job);}
 expect(new Set(sustained.map(s=>s.id)).size).toBe(60);expect(sustained.length).toBe(180);expect(errors).toEqual([]);
});
test('genuine Mage cancellation and loaded zone reset',async({page})=>{
 await setup(page);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.keyboard.press('k');await page.locator('[data-slot-for="mage-10"]').evaluate((el:HTMLSelectElement)=>el.value='0');await page.locator('[data-assign="mage-10"]').click();await page.keyboard.press('Escape');
 // Nearest target within authored skill range; compare target HP at accepted cast start.
 await page.keyboard.press('Tab');const before=await page.evaluate(()=>(window as any).mossvale.snapshot());const selectedBefore=before.monsters.find((m:any)=>m.id===before.target);expect(Math.hypot(selectedBefore.x-before.x,selectedBefore.z-before.z)).toBeLessThanOrEqual(8);await page.keyboard.press('1');await page.waitForFunction(()=>!!(window as any).mossvale.snapshot().cast,{},{timeout:10000});const accepted=await page.evaluate(()=>(window as any).mossvale.snapshot());expect(accepted.cast.skillId).toBe('mage-10');expect(accepted.cast.remaining).toBeGreaterThan(0);expect(accepted.skillCooldowns['mage-10']).toBeGreaterThan(0);await page.keyboard.down('d');await page.waitForFunction(()=>!(window as any).mossvale.snapshot().cast,{},{timeout:10000});await page.keyboard.up('d');await page.waitForFunction(()=>!(window as any).mossvale.snapshot().skillMotion,{},{timeout:10000});const cancelled=await page.evaluate(()=>(window as any).mossvale.snapshot());expect(cancelled.x).toBeGreaterThan(accepted.x);expect(cancelled.cast).toBeNull();expect(cancelled.skillMotion).toBeNull();expect(cancelled.mp).toBeLessThan(before.mp);const targetBefore=accepted.monsters.find((m:any)=>m.id===accepted.cast.targetId),targetAfter=cancelled.monsters.find((m:any)=>m.id===accepted.cast.targetId);expect(targetAfter.hp).toBe(targetBefore.hp);await page.screenshot({path:`${out}/cancelled-real-mage-cast.png`});writeFileSync(`${out}/cancellation-final.json`,JSON.stringify({before,accepted,cancelled,errors},null,2));console.log('QA_CANCELLED_REAL_CAST');await page.waitForFunction(()=>(window as any).mossvale.snapshot().vfx.active===0,{},{timeout:10000});const settled=await page.evaluate(()=>(window as any).mossvale.snapshot());expect(settled.monsters.find((m:any)=>m.id===accepted.cast.targetId).hp).toBe(targetBefore.hp);writeFileSync(`${out}/cancellation-final.json`,JSON.stringify({before,accepted,cancelled,settled,errors},null,2));
 await page.locator('#untarget').evaluate((b:HTMLElement)=>b.click());await page.locator('[data-panel="settings"]').click();await page.getByRole('combobox',{name:'Graphics quality'}).click({timeout:20000});await page.getByRole('option',{name:'low',exact:true}).click({timeout:20000});await page.keyboard.press('Escape');await page.keyboard.press('m');await page.locator('[data-travel="town"]').click();await page.keyboard.press('Escape');await page.waitForFunction(()=>{const s=(window as any).mossvale.snapshot();return Math.hypot(s.x,s.z+11)<2.9},{},{timeout:30000});await page.keyboard.press('m');await page.locator('[data-travel="town"]').click();await page.keyboard.press('Escape');await page.waitForFunction(()=>{const s=(window as any).mossvale.snapshot();return s.zone==='town'&&s.skillMotion===null&&s.modelErrors===0&&s.riggedActors>=s.monsters.length+3},{},{timeout:45000});const zoneReset=await page.evaluate(()=>(window as any).mossvale.snapshot());expect(zoneReset.motionPoses).toEqual([]);expect(errors).toEqual([]);await page.screenshot({path:`${out}/zone-reset-town.png`});writeFileSync(`${out}/performance-cancel-zone.json`,JSON.stringify({environment:'Headless Chromium ANGLE SwiftShader software renderer. These numbers are comparative software-renderer measurements, not real player hardware performance.',cancellation:{before,accepted,cancelled,settled},zoneReset,errors},null,2));
});
