import {test,expect} from '@playwright/test';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
const out='artifacts/dynamic-skills';
const baseFixture=readFileSync('tests/dynamic-skills-preview.spec.ts','utf8').split('const fixture=`')[1].split('`;\nfor(const job')[0];
const fixture=baseFixture.replace("phase:'release',progress:p", "phase:play?.anticipation?'anticipation':'release',progress:p").replace("play.elapsed/skillRecoveryDuration(play.skill.stage)", "play.elapsed/(play.anticipation?(play.skill.cast||1):skillRecoveryDuration(play.skill.stage))").replace("window.review={engine", "window.review={anticipate(id){const skill=skills[job].find(s=>s.id===id);held=null;vfx.clear();vfx.anticipation(skill,job,0,0);play={skill,elapsed:0,anticipation:true};},engine");
for(const job of ['swordsman','mage','archer'])test(`${job}: short continuous real-time rig release movie both branches`,async({browser})=>{
 mkdirSync(out,{recursive:true});const context=await browser.newContext({viewport:{width:720,height:600},recordVideo:{dir:out+'/video',size:{width:720,height:600}}}),page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>{errors.push(e.message);console.error('QA_PAGE_ERROR',e.message)});await page.route('**/dynamic-motion.html*',r=>r.fulfill({contentType:'text/html',body:fixture}));await page.goto(`/dynamic-motion.html?job=${job}`);await page.waitForFunction(()=>(window as any).review?.library.active===1,{},{timeout:45000});await page.evaluate(()=>(window as any).review.cameraAt(.65));const samples:any[]=[];const frozenId=`${job}-10`;await page.evaluate(id=>(window as any).review.preview(id,.4),frozenId);const frozen=await page.evaluate(()=>(window as any).review.describe());await page.evaluate(id=>(window as any).review.play(id),frozenId);const resumed:any[]=[];for(let n=0;n<3;n++){await page.waitForFunction(p=>{const r=(window as any).review;const c=r.describe().poses[0]?.context;return c?.frozen===false&&c.phase==='release'&&c.progress>=p},[.08,.2,.32][n],{timeout:10000});resumed.push(await page.evaluate(()=>(window as any).review.describe()));}expect(resumed.some(r=>JSON.stringify(r.rigJointTransforms)!==JSON.stringify(frozen.rigJointTransforms))).toBe(true);if(job==='mage'){await page.evaluate(()=>(window as any).review.anticipate('mage-10'));for(let n=0;n<9;n++){await page.waitForFunction(p=>{const c=(window as any).review.describe().poses[0]?.context;return c?.phase==='anticipation'&&c.frozen===false&&c.progress>=p},(n+1)*.1,{timeout:10000});samples.push({id:'mage-10',phase:'anticipation',elapsed:(n+1)*.1,...await page.evaluate(()=>(window as any).review.describe())});}}
 for(const branch of ['', 'b-'])for(const stage of [1,4,7,10]){const id=`${job}-${branch}${stage}`;await page.evaluate(id=>(window as any).review.play(id),id);await page.waitForFunction(id=>{const c=(window as any).review.describe().poses[0]?.context;return c?.skillId===id&&c.frozen===false},id,{timeout:10000});for(let n=0;n<7;n++){await page.waitForFunction(p=>{const d=(window as any).review.describe();return !d.poses.length||d.poses[0].context.progress>=p},(n+1)/8,{timeout:10000});samples.push({id,progress:(n+1)/8,...await page.evaluate(()=>(window as any).review.describe())});}}
 if(job==='mage'){const charge=samples.filter(s=>s.phase==='anticipation');expect(charge[3].poses[0]?.isPlaying).toBe(true);expect(charge[6].poses[0]?.isPlaying).toBe(true);expect(charge[8].poses[0]?.isPlaying).toBe(true);expect(JSON.stringify(charge[3].rigJointTransforms)).not.toBe(JSON.stringify(charge[6].rigJointTransforms));expect(JSON.stringify(charge[6].rigJointTransforms)).not.toBe(JSON.stringify(charge[8].rigJointTransforms));}expect(samples.every(s=>!s.poses.length||s.poses[0].context.skillId===s.id)).toBe(true);expect(errors).toEqual([]);expect(samples.every(s=>s.modelErrors===0&&s.actorPosition.every((n:number)=>n===0))).toBe(true);writeFileSync(`${out}/live-motion-${job}.json`,JSON.stringify({environment:'isolated render-only continuous release, Babylon rig animation and local choreography',samples,frozenResume:{frozen,resumed},errors},null,2));const v=page.video();await context.close();if(v)await v.saveAs(`${out}/live-motion-${job}.webm`);
});
