import {test,expect} from '@playwright/test';
import {Simulation} from '../src/simulation';
import {normalMonsterBalance,zones,species} from '../src/game/content';
import {rollEquipmentDrops,gearById} from '../src/game/equipment';
import {itemMigrationConfig,salvageConfig,skillRankConfig,contentConfig,equipmentConfig,progression,craftingConfig,refinement,classConfig,economy,validateConfiguration} from '../src/config/balance';
import {transact,MONSTER_BALANCE_REVISION,ROOM_LAYOUT_REVISION} from '../server/realm';
import {shareKill} from '../server/community';
import type {Realm} from '../server/protocol';
import type {RealmStore} from '../server/store';
const tiers=[['glade',20,10],['orchard',40,30],['marsh',60,50],['frost',80,70],['ruins',100,90]] as const;
test('each themed elite uses new level and same-level normal multipliers, gold formula, unchanged XP rule',()=>{
 const sim=new Simulation(()=>.5,undefined,null);
 for(const [zone,level] of tiers)for(const kind of zones[zone].species.filter(k=>species[k].boss||species[k].miniBoss)){const m=sim.monsterSpec(kind),base=normalMonsterBalance(level),boss=!!m.boss;expect(m.level).toBe(level);expect([m.hp,m.atk,m.defense,m.gold]).toEqual([base.hp*(boss?30:15),base.atk*(boss?6:3),base.defense*(boss?2:1.5),level*(boss?50:30)]);expect(m.xp).toBe(progression.levels[level-1].monsterXp*(boss?12:4));}
});
test('all elite gear levels have exactly two weighted drops, uniform slots, independent duplicate identities',()=>{
 for(const [,level,gearLevel] of tiers)for(const tier of ['boss','mini'] as const){const rows=equipmentConfig.eliteDrops[tier];let lower=0;for(const row of rows){const mid=lower+row.weight/2;for(const slotRoll of [0,.999999]){const groups=equipmentConfig.eliteDrops.groups[row.group as 'attack'|'defense'],slot=slotRoll===0?groups[0]:groups.at(-1)!;
  const one=[mid,slotRoll];if(slot==='weapon')one.push(.999999);for(let n=0;n<(row.rarity==='rare'?2:3);n++)one.push(.5,.5);const queue=[...one,...one],drops=rollEquipmentDrops(level,tier,()=>queue.shift()??.999999);expect(drops).toHaveLength(2);expect(drops.map(d=>d.rarity)).toEqual([row.rarity,row.rarity]);expect(drops.map(d=>gearById(d.gearId!)!.slot)).toEqual([slot,slot]);expect(drops.map(d=>gearById(d.gearId!)!.level)).toEqual([gearLevel,gearLevel]);expect(drops[0].gearId).toBe(drops[1].gearId);expect(drops[0].id).not.toBe(drops[1].id);
 }lower+=row.weight;}
  for(const rng of [()=>0,()=>.999999]){const drops=rollEquipmentDrops(level,tier,rng);expect(drops).toHaveLength(2);expect(drops.every(d=>d.rarity==='rare'||d.rarity==='epic')).toBe(true);}
 }
});
test('weighted group exact boundaries choose next group; totals and bad edits validate',()=>{
 for(const tier of ['boss','mini'] as const){let threshold=0;const rows=equipmentConfig.eliteDrops[tier];for(let i=0;i<rows.length-1;i++){threshold+=rows[i].weight;const queue=[threshold,.999999,...Array(4).fill(.5),.999999,.999999,...Array(4).fill(.5)];const drop=rollEquipmentDrops(20,tier,()=>queue.shift()??.999999)[0];expect(drop.rarity).toBe(rows[i+1].rarity);expect(equipmentConfig.eliteDrops.groups[rows[i+1].group as 'attack'|'defense']).toContain(gearById(drop.gearId!)!.slot);}}
 const boundary=[.58,.999999,...Array(4).fill(.5),.999999,.999999,...Array(4).fill(.5)];const bossBoundary=rollEquipmentDrops(20,'boss',()=>boundary.shift()??.999999)[0];expect(bossBoundary.rarity).toBe('epic');expect(gearById(bossBoundary.gearId!)!.slot).toBe('boots');
 const config=()=>structuredClone({itemMigration:itemMigrationConfig,salvage:salvageConfig,skillRanks:skillRankConfig,content:contentConfig,equipment:equipmentConfig,progression,crafting:craftingConfig,refinement,classes:classConfig,economy});for(const mutate of [(c:ReturnType<typeof config>)=>c.equipment.eliteDrops.count=3,c=>c.equipment.eliteDrops.boss[0].weight=.5,c=>c.equipment.eliteDrops.mini[0].rarity='legend',c=>c.content.normalBalance.boss.goldPerLevel=0]){const c=config();mutate(c);expect(()=>validateConfiguration(c)).toThrow(/Invalid balance config/);}
});
test('solo and party elites award exactly two unique pieces and configured gold, including mini bosses',()=>{
 for(const tier of ['boss','mini'] as const){const s=new Simulation(()=>0,undefined,null),m=s.monsters.find(m=>tier==='boss'?species[m.kind].boss:species[m.kind].miniBoss)!;s.x=m.x;s.z=m.z;const gold=s.save.gold;s.hit(m,1e9);expect(s.save.gold-gold).toBe(20*(tier==='boss'?50:30));expect(s.loot.filter(l=>l.item?.gearId)).toHaveLength(2);
  const a=new Simulation(()=>0,undefined,null),b=new Simulation(()=>0,undefined,null),elite=a.monsters.find(m=>tier==='boss'?species[m.kind].boss:species[m.kind].miniBoss)!;a.x=b.x=elite.x;a.z=b.z=elite.z;a.rollStoneLoot=()=>undefined;a.rollMaterialLoot=()=>[];a.hasLegacyDrop=()=>false;const realm={community:{parties:[{id:'p',leader:'a',members:['a','b'],invites:[],lootCursor:0}],friends:{},requests:{},trades:[],listings:[]},ledger:[]} as unknown as Realm;const pa={id:'a',room:'glade'},pb={id:'b',room:'glade'};expect(shareKill(realm,pa as any,elite,[{p:pa as any,sim:a},{p:pb as any,sim:b}],1000)).toBe(true);const drops=[...a.save.items,...b.save.items].filter(i=>i.gearId);expect(drops).toHaveLength(2);expect(new Set(drops.map(d=>d.id)).size).toBe(2);expect(a.save.items.filter(i=>i.gearId)).toHaveLength(1);expect(b.save.items.filter(i=>i.gearId)).toHaveLength(1);expect(a.save.gold).toBe(120+20*(tier==='boss'?50:30)/2);
 }
});
class Store implements RealmStore {realm:Realm|null=null;revision=0;async read(){return this.realm?{realm:structuredClone(this.realm),revision:this.revision}:null;}async create(r:Realm){this.realm=structuredClone(r);}async commit(rev:number,r:Realm){if(rev!==this.revision)return false;this.realm=structuredClone(r);this.revision++;return true;}}
test('revision3 HP migration preserves fractions, dead/status timers, overrides, inventory and progress once',async()=>{
 const store=new Store(),id={id:'keeper',name:'Keeper'};await transact(store,id,{connect:true},1000);const realm=store.realm!,room=realm.rooms!.glade;room.layoutRevision=5;room.balanceRevision=3;const boss=room.monsters.find(m=>species[m.kind].boss)!,mini=room.monsters.find(m=>species[m.kind].miniBoss)!;boss.hp=contentConfig.normalBalance.revision3Hp[boss.kind]*.25;boss.poison=3;boss.poisonDamage=7;mini.alive=false;mini.hp=0;mini.respawn=41;const normal=room.monsters[0];normal.hp=contentConfig.normalBalance.revision3Hp[normal.kind]*.5;realm.players.keeper.actor.save.gold=555;const saved=structuredClone(realm.players.keeper.actor.save);const snap=await transact(store,id,{},1000),current=store.realm!.rooms!.glade;expect(current.layoutRevision).toBe(ROOM_LAYOUT_REVISION);expect(current.balanceRevision).toBe(MONSTER_BALANCE_REVISION);const updated=current.monsters.find(m=>m.kind===boss.kind)!;expect(updated.hp).toBe(new Simulation(()=>0,undefined,null).monsterSpec(boss.kind).hp*.25);expect(updated.poison).toBe(3);expect(updated.poisonDamage).toBe(7);const updatedMini=current.monsters.find(m=>m.kind===mini.kind)!;expect(updatedMini.alive).toBe(false);expect(updatedMini.respawn).toBe(41);expect(snap.player.actor.save).toEqual(saved);expect(current.monsters[0].hp).toBe(contentConfig.normalBalance.revision3Hp[normal.kind]*.5);const hp=updated.hp,session=snap.player.session.id;await transact(store,id,{},1000);expect(store.realm!.rooms!.glade.monsters.find(m=>m.kind===boss.kind)!.hp).toBe(hp);expect(store.realm!.players.keeper.session.id).toBe(session);
});
