import {test,expect} from '@playwright/test';
import {Simulation,type Item} from '../src/simulation';
import {gearById,rollGear} from '../src/game/equipment';
const fixture=()=>{const sim=new Simulation(()=>.5,undefined,null);sim.save.level=100;sim.save.zone='town';for(let n=0;n<52;n++){const id=n===0?'thornwood-blade':n===1?'starfall-helmet':'thornwood-charm',definition=gearById(id)!;sim.addEquipmentItem({...rollGear(id,n===0?'rare':'ancient',()=>.6),name:definition.name,icon:definition.icon,count:1});}return sim.save;};
test('bag has 48 cells per page, three pages, floating comparison, persistent left-click details and right-click equip/unequip',async({page})=>{
 const save=fixture();await page.addInitScript(save=>{localStorage.setItem('mossvale-save',JSON.stringify(save));localStorage.setItem('mossvale-quality','low')},save);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?practice=1');await page.waitForFunction(()=>{const s=(window as any).mossvale?.snapshot();return s&&s.riggedActors===s.modelsExpected&&s.modelErrors===0},{},{timeout:60000});await expect(page.locator('#hp-text')).toContainText('/');await page.keyboard.press('i');
 await expect(page.locator('.inventory-grid > .item')).toHaveCount(48);await expect(page.locator('[data-bag-page]')).toHaveCount(3);await expect(page.locator('.worn-slot')).toHaveCount(6);await expect(page.locator('#item-detail')).toHaveCount(0);
 const helmet=save.items.find(i=>i.gearId==='starfall-helmet')!;await page.locator(`.inventory-grid [data-item="${helmet.id}"]`).hover();await expect(page.getByRole('tooltip')).toBeVisible();await expect(page.getByRole('tooltip')).toContainText('Legend');await expect(page.getByRole('tooltip')).toContainText('SECONDARY STATS · 4');await expect(page.getByRole('tooltip')).toContainText('vs equipped');await page.screenshot({path:'artifacts/inventory-hover.png'});
 await page.locator(`.inventory-grid [data-item="${helmet.id}"]`).click();await expect(page.locator('#item-details')).toBeVisible();expect(await page.evaluate(()=>(window as any).mossvale.snapshot().equipped.helmet)).not.toBe(helmet.id);await page.mouse.move(0,0);await expect(page.locator('#item-details')).toBeVisible();await expect(page.locator('#item-details [data-item-action=salvage]')).toBeDisabled();await page.locator('#item-details [data-item-action=close]').click();await page.locator(`.inventory-grid [data-item="${helmet.id}"]`).click({button:'right'});await expect.poll(()=>page.evaluate(()=>(window as any).mossvale.snapshot().equipped.helmet)).toBe(helmet.id);await expect(page.locator(`.worn-equipment [data-item="${helmet.id}"]`)).toBeVisible();await page.mouse.move(0,0);await expect(page.getByRole('tooltip')).toBeHidden();await page.screenshot({path:'artifacts/inventory-equipped.png'});
 await page.getByRole('button',{name:'Inventory page 2',exact:true}).click();await expect(page.locator('.inventory-grid > .item')).toHaveCount(48);await expect(page.locator('.bag-pages')).toContainText('PAGE 2 / 3');await page.getByRole('button',{name:'Inventory page 3',exact:true}).click();await expect(page.locator('.inventory-grid > .item')).toHaveCount(48);await expect(page.locator('.inventory-grid [data-item]')).toHaveCount(0);
 await page.locator('[data-unequip="helmet"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).mossvale.snapshot().equipped.helmet)).toBeNull();expect(errors).toEqual([]);
});
test('mobile keeps the eight-column bag and six equipped slots inside the viewport',async({page})=>{
 await page.setViewportSize({width:390,height:844});const save=fixture();await page.addInitScript(save=>{localStorage.setItem('mossvale-save',JSON.stringify(save));localStorage.setItem('mossvale-quality','low')},save);await page.goto('/?practice=1');await page.waitForFunction(()=>{const s=(window as any).mossvale?.snapshot();return s&&s.riggedActors===s.modelsExpected&&s.modelErrors===0},{},{timeout:60000});await page.locator('[data-panel="inventory"]').click();await expect(page.locator('.inventory-grid > .item')).toHaveCount(48);
 const fit=await page.locator('.inventory-grid').evaluate(e=>{const rect=e.getBoundingClientRect();return {columns:getComputedStyle(e).gridTemplateColumns.split(' ').length,left:rect.left,right:rect.right,width:document.documentElement.scrollWidth}});expect(fit.columns).toBe(8);expect(fit.left).toBeGreaterThanOrEqual(0);expect(fit.right).toBeLessThanOrEqual(390);expect(fit.width).toBeLessThanOrEqual(390);await page.mouse.move(0,0);await page.screenshot({path:'artifacts/inventory-mobile-new.png'});
});

test('icon details sell one potion, right-click uses, salvage returns both matching materials and refine selects this gear',async({page})=>{
 const sim=new Simulation(()=>.5,undefined,null);sim.save.level=100;sim.save.zone='town';sim.save.hp=1;
 for(const [gearId,rarity] of [['thornwood-blade','common'],['thornwood-coat','rare']] as const){const g=gearById(gearId)!;sim.addEquipmentItem({...rollGear(gearId,rarity,()=>.5),name:g.name,icon:g.icon,count:1});}
 const weapon=sim.save.items.find(i=>i.gearId==='thornwood-blade')!,armor=sim.save.items.find(i=>i.gearId==='thornwood-coat')!;
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1200,height:800});await page.addInitScript(save=>{localStorage.setItem('mossvale-save',JSON.stringify(save));localStorage.setItem('mossvale-quality','low')},sim.save);
 await page.goto('/?practice=1');await page.waitForFunction(()=>{const s=(window as any).mossvale?.snapshot();return s&&s.riggedActors===s.modelsExpected&&s.modelErrors===0},{},{timeout:60000});await page.keyboard.press('i');
 const snapshot=()=>page.evaluate(()=>(window as any).mossvale.snapshot());const count=async(name:string,rarity='common')=>(await snapshot()).items.filter((i:any)=>i.name===name&&(i.rarity||'common')===rarity).reduce((n:number,i:any)=>n+i.count,0);
 const before=(await snapshot()),potions=await count('Red potion');const potion=page.locator('.inventory-grid [data-item="Red potion"]');await potion.click();await page.mouse.move(0,0);await expect(page.locator('#item-details')).toBeVisible();await expect(page.locator('#item-details [data-item-action=use]')).toBeVisible();await expect(page.locator('#item-details [data-item-action=salvage]')).toHaveCount(0);
 expect(await page.locator('#item-details [data-item-action]').evaluateAll(nodes=>nodes.filter(n=>n.getAttribute('data-item-action')!=='close').every(n=>n.textContent?.trim()===''&&!!n.getAttribute('aria-label')))).toBe(true);
 await page.locator('#item-details [data-item-action=sell]').click();expect(await count('Red potion')).toBe(potions-1);expect((await snapshot()).gold).toBeGreaterThan(before.gold);await page.locator('#item-details [data-item-action=close]').click();await potion.click({button:'right'});expect(await count('Red potion')).toBe(potions-2);expect((await snapshot()).hp).toBeGreaterThan(before.hp);
 await page.locator(`.inventory-grid [data-item="${weapon.id}"]`).click();await expect(page.locator('#item-details [data-item-action=salvage]')).toBeEnabled();await page.screenshot({path:'artifacts/inventory-actions-desktop.png'});await page.locator('#item-details [data-item-action=salvage]').click();expect((await snapshot()).items.some((i:any)=>i.id===weapon.id)).toBe(false);expect(await count('Shade essence')).toBe(2);expect(await count('Rune stone')).toBe(2);
 await page.locator(`.inventory-grid [data-item="${armor.id}"]`).click();await page.locator('#item-details [data-item-action=refine]').click();await expect(page.locator('#refine-item')).toHaveValue(armor.id!);await page.keyboard.press('Escape');await page.keyboard.press('i');
 await page.setViewportSize({width:390,height:844});await page.locator(`.inventory-grid [data-item="${armor.id}"]`).click();const bounds=(await page.locator('#item-details').boundingBox())!;expect(bounds.x).toBeGreaterThanOrEqual(0);expect(bounds.x+bounds.width).toBeLessThanOrEqual(390);expect(bounds.y+bounds.height).toBeLessThanOrEqual(844);await page.screenshot({path:'artifacts/inventory-actions-mobile.png'});
 await page.locator('#item-details [data-item-action=salvage]').click();expect(await count('Shade essence','rare')).toBe(1);expect(await count('Sky feather','rare')).toBe(1);expect(await count('Rune stone','rare')).toBe(0);expect(errors).toEqual([]);
});
