import {test,expect} from '@playwright/test';
import {Simulation,type Item} from '../src/simulation';
import {gearById,rollGear} from '../src/game/equipment';
const fixture=()=>{const sim=new Simulation(()=>.5,undefined,null);sim.save.level=100;for(let n=0;n<52;n++){const id=n===0?'thornwood-blade':n===1?'starfall-helmet':'thornwood-charm',definition=gearById(id)!;sim.addEquipmentItem({...rollGear(id,n===0?'rare':'legend',()=>.6),name:definition.name,icon:definition.icon,count:1});}return sim.save;};
test('bag has 48 cells per page, three pages, floating comparison and one-click equip/unequip',async({page})=>{
 const save=fixture();await page.addInitScript(save=>{localStorage.setItem('mossvale-save',JSON.stringify(save));localStorage.setItem('mossvale-quality','low')},save);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?practice=1');await expect(page.locator('#hp-text')).toContainText('/');await page.keyboard.press('i');
 await expect(page.locator('.inventory-grid > .item')).toHaveCount(48);await expect(page.locator('[data-bag-page]')).toHaveCount(3);await expect(page.locator('.worn-slot')).toHaveCount(6);await expect(page.locator('#item-detail')).toHaveCount(0);
 const helmet=save.items.find(i=>i.gearId==='starfall-helmet')!;await page.locator(`.inventory-grid [data-item="${helmet.id}"]`).hover();await expect(page.getByRole('tooltip')).toBeVisible();await expect(page.getByRole('tooltip')).toContainText('Legend');await expect(page.getByRole('tooltip')).toContainText('SECONDARY STATS · 3');await expect(page.getByRole('tooltip')).toContainText('vs equipped');await page.screenshot({path:'artifacts/inventory-hover.png'});
 await page.locator(`.inventory-grid [data-item="${helmet.id}"]`).click();await expect.poll(()=>page.evaluate(()=>(window as any).mossvale.snapshot().equipped.helmet)).toBe(helmet.id);await expect(page.locator(`.worn-equipment [data-item="${helmet.id}"]`)).toBeVisible();await page.mouse.move(0,0);await expect(page.getByRole('tooltip')).toBeHidden();await page.screenshot({path:'artifacts/inventory-equipped.png'});
 await page.getByRole('button',{name:'Inventory page 2',exact:true}).click();await expect(page.locator('.inventory-grid > .item')).toHaveCount(48);await expect(page.locator('.bag-pages')).toContainText('PAGE 2 / 3');await page.getByRole('button',{name:'Inventory page 3',exact:true}).click();await expect(page.locator('.inventory-grid > .item')).toHaveCount(48);await expect(page.locator('.inventory-grid [data-item]')).toHaveCount(0);
 await page.locator('[data-unequip="helmet"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).mossvale.snapshot().equipped.helmet)).toBeNull();expect(errors).toEqual([]);
});
test('mobile keeps the eight-column bag and six equipped slots inside the viewport',async({page})=>{
 await page.setViewportSize({width:390,height:844});const save=fixture();await page.addInitScript(save=>{localStorage.setItem('mossvale-save',JSON.stringify(save));localStorage.setItem('mossvale-quality','low')},save);await page.goto('/?practice=1');await page.locator('[data-panel="inventory"]').click();await expect(page.locator('.inventory-grid > .item')).toHaveCount(48);
 const fit=await page.locator('.inventory-grid').evaluate(e=>{const rect=e.getBoundingClientRect();return {columns:getComputedStyle(e).gridTemplateColumns.split(' ').length,left:rect.left,right:rect.right,width:document.documentElement.scrollWidth}});expect(fit.columns).toBe(8);expect(fit.left).toBeGreaterThanOrEqual(0);expect(fit.right).toBeLessThanOrEqual(390);expect(fit.width).toBeLessThanOrEqual(390);await page.mouse.move(0,0);await page.screenshot({path:'artifacts/inventory-mobile-new.png'});
});
