import {test,expect} from '@playwright/test';
import {Simulation} from '../src/simulation';
test('category tabs filter the bag, retain 48 cells and reset pagination',async({page})=>{
 const sim=new Simulation(()=>.5,undefined,null);sim.addItem('Sprout Blade','swords');sim.addItem('Field Coat','field-coat');sim.addItem('Leaf Charm','leaf-charm');sim.addItem('Dew jelly','jelly');sim.addItem('Common refine stone','ice-shard',10);await page.addInitScript(save=>{localStorage.setItem('mossvale-save',JSON.stringify(save));localStorage.setItem('mossvale-quality','low')},sim.save);
 await page.goto('/?practice=1');await page.keyboard.press('i');await expect(page.getByRole('tab')).toHaveCount(7);await page.getByRole('button',{name:'Inventory page 2',exact:true}).click();
 for(const [category,name] of [['weapon','Sprout Blade'],['armor','Field Coat'],['accessory','Leaf Charm'],['material','Dew jelly'],['refine','Common refine stone']]){await page.locator(`[data-bag-category="${category}"]`).click();await expect(page.locator('.inventory-grid [data-item]')).toHaveCount(1);await expect(page.locator('.inventory-grid [data-item]')).toHaveAttribute('data-item',category==='weapon'||category==='armor'||category==='accessory'?sim.save.items.find(i=>i.name===name)!.id!:name);await expect(page.locator('.inventory-grid > .item')).toHaveCount(48);await expect(page.locator('.bag-pages')).toContainText('PAGE 1 / 3');}
 await page.locator('[data-bag-category="all"]').click();await page.screenshot({path:'artifacts/item-category-tabs.png'});
});
test('online local admin can grant items through UI and ordinary account does not see admin tools',async({page,request})=>{
 await page.addInitScript(()=>localStorage.setItem('mossvale-quality','low'));await page.goto('/?online=1');await expect(page.locator('#hp-text')).toContainText('/');await page.locator('[data-panel="settings"]').click();await page.locator('[data-panel="admin"]').click();await expect(page.locator('#spawn-form')).toBeVisible();await page.screenshot({path:'artifacts/admin-item-tools.png'});
 await page.selectOption('#spawn-category','refine');await page.selectOption('#spawn-item','refine:rare');await page.fill('#spawn-count','7');const before=await page.evaluate(()=>(window as any).mossvale.snapshot().items.find((i:any)=>i.name==='Rare refine stone')?.count||0);await page.getByRole('button',{name:'Spawn into my bag'}).click();await expect.poll(()=>page.evaluate(()=>(window as any).mossvale.snapshot().items.find((i:any)=>i.name==='Rare refine stone')?.count||0)).toBe(before+7);
 await page.reload();await expect.poll(()=>page.evaluate(()=>(window as any).mossvale?.snapshot().items.find((i:any)=>i.name==='Rare refine stone')?.count||0)).toBe(before+7);
 const ordinary=await request.post('http://127.0.0.1:8787/api/game',{headers:{cookie:'mossvale-dev=ordinary-ui-test','oai-authenticated-user-email':'local-admin@localhost'},data:{connect:true}});expect((await ordinary.json()).admin).toBe(false);
 await page.context().addCookies([{name:'mossvale-dev',value:'ordinary-ui-test',url:'http://127.0.0.1:5173'}]);await page.reload();await expect(page.locator('#hp-text')).toContainText('/');await page.locator('[data-panel="settings"]').click();await expect(page.locator('[data-panel="admin"]')).toHaveCount(0);
});
