// Independent render-only QA fixture. Never writes Simulation state.

import {Engine} from '@babylonjs/core/Engines/engine.js';
import {Scene} from '@babylonjs/core/scene.js';
import {FreeCamera} from '@babylonjs/core/Cameras/freeCamera.js';
import {Vector3} from '@babylonjs/core/Maths/math.vector.js';
import {Color3,Color4} from '@babylonjs/core/Maths/math.color.js';
import {HemisphericLight} from '@babylonjs/core/Lights/hemisphericLight.js';
import {DirectionalLight} from '@babylonjs/core/Lights/directionalLight.js';
import {MeshBuilder} from '@babylonjs/core/Meshes/meshBuilder.js';
import {StandardMaterial} from '@babylonjs/core/Materials/standardMaterial.js';
import {TransformNode} from '@babylonjs/core/Meshes/transformNode.js';
import {ModelLibrary} from '../src/render/model-library.ts';
import {SkillVFX} from '../src/render/skill-vfx.ts';
import {skillRecoveryDuration} from '../src/render/skill-choreography.ts';
import {skills} from '../src/game/classes.ts';
const engine=new Engine(document.querySelector('canvas'),true),scene=new Scene(engine);scene.clearColor=new Color4(.72,.8,.78,1);scene.useRightHandedSystem=true;
const camera=new FreeCamera('qa-camera',new Vector3(4,3.8,6),scene);camera.minZ=.05;camera.setTarget(new Vector3(0,1,1));
new HemisphericLight('sky',new Vector3(0,1,0),scene).intensity=.85;new DirectionalLight('sun',new Vector3(-1,-2,1),scene).intensity=.8;
const ground=MeshBuilder.CreateGround('ground',{width:18,height:18},scene),gm=new StandardMaterial('ground-material',scene);gm.diffuseColor=new Color3(.32,.46,.38);ground.material=gm;
const library=new ModelLibrary(scene),vfx=new SkillVFX(scene),job=new URLSearchParams(location.search).get('job'),actor=new TransformNode('qa-authoritative-actor',scene);library.attach(job,actor);
let held=null,play=null,last=performance.now();const cameraAt=(angle)=>{camera.position=new Vector3(Math.sin(angle)*7,3.8,Math.cos(angle)*7);camera.setTarget(new Vector3(0,1,1));};
function pose(skill,p,frozen){if(frozen)for(const g of scene.animationGroups)for(const e of g.targetedAnimations){e.animation.enableBlending=false;}library.setSkillMotion(actor,{job,stage:skill.stage,branch:skill.branch,effect:skill.effect,phase:play?.anticipation?'anticipation':'release',progress:p,skillId:skill.id,duration:skillRecoveryDuration(skill.stage),frozen});library.animate(actor,false,120,false,false,.016);}
function preview(id,p){const skill=skills[job].find(s=>s.id===id);vfx.clear();vfx.release(skill,job,0,0,0,2);vfx.update(p*skillRecoveryDuration(skill.stage));held={skill,p};play=null;pose(skill,p,true);document.querySelector('#label').textContent=skill.name+' · '+Math.round(p*100)+'%';scene.render();}
engine.runRenderLoop(()=>{const now=performance.now(),dt=Math.min(.05,(now-last)/1000);last=now;if(play){play.elapsed+=dt;const p=Math.min(1,play.elapsed/(play.anticipation?(play.skill.cast||1):skillRecoveryDuration(play.skill.stage)));pose(play.skill,p,false);if(p>=1){library.setSkillMotion(actor,null);library.animate(actor,false,120,false,false,dt);play=null;}}if(!held)vfx.update(dt);scene.render();});
window.review={anticipate(id){const skill=skills[job].find(s=>s.id===id);held=null;document.querySelector('#label').textContent=skill.name+' · live anticipation';vfx.clear();vfx.anticipation(skill,job,0,0);play={skill,elapsed:0,anticipation:true};},engine,scene,library,vfx,actor,camera,Vector3,preview,cameraAt,quality(low){library.setLowQuality(low);vfx.setLowQuality(low)},play(id){const skill=skills[job].find(s=>s.id===id);held=null;document.querySelector('#label').textContent=skill.name+' · live release';vfx.clear();vfx.release(skill,job,0,0,0,2);play={skill,elapsed:0};},describe(){let bodyMinY=Infinity,bodyMaxY=-Infinity;const bodyBounds=[];for(const m of actor.getChildMeshes().filter(m=>m.isEnabled()&&m.isVisible&&m.getTotalVertices()>0)){const a=m.getPositionData?.(true,true);if(!a)continue;m.computeWorldMatrix(true);let meshMinY=Infinity,meshMaxY=-Infinity;for(let i=0;i<a.length;i+=3){const q=Vector3.TransformCoordinates(new Vector3(a[i],a[i+1],a[i+2]),m.getWorldMatrix());meshMinY=Math.min(meshMinY,q.y);meshMaxY=Math.max(meshMaxY,q.y);bodyMinY=Math.min(bodyMinY,q.y);bodyMaxY=Math.max(bodyMaxY,q.y);}bodyBounds.push({name:m.name,skeletonName:m.skeleton?.name||null,parentName:m.parent?.name,minY:meshMinY,maxY:meshMaxY,isEnabled:m.isEnabled(),isVisible:m.isVisible,visibility:m.visibility,parentEnabled:m.parent?.isEnabled(),scale:m.scaling.asArray(),matrixDeterminant:m.getWorldMatrix().determinant()});}const meshes=scene.meshes.filter(m=>m.metadata?.vfxShape&&m.isEnabled());return {elapsedMs:performance.now(),modelErrors:library.errors,loaded:library.active,actorPosition:actor.position.asArray(),actorRotation:actor.rotation.asArray(),bodyMinY,bodyMaxY,bodyBounds,poses:library.motionDiagnostics,vfx:vfx.diagnostics,sceneMeshes:scene.meshes.length,sceneMaterials:scene.materials.length,rigJointTransforms:actor.getDescendants().filter(n=>/hip|hand|foot|head/i.test(n.name)&&n.position).map(n=>({name:n.name,position:n.position.asArray(),rotation:n.rotationQuaternion?.asArray()||n.rotation.asArray()})),rigBones:scene.skeletons.flatMap(s=>s.bones.filter(b=>/head|hand|foot|hip/i.test(b.name)).map(b=>({name:b.name,position:b.getAbsolutePosition().asArray()}))),shapes:meshes.map(m=>{const a=m.getVerticesData('position'),mins=[Infinity,Infinity,Infinity],maxs=[-Infinity,-Infinity,-Infinity];for(let i=0;i<a.length;i++) {mins[i%3]=Math.min(mins[i%3],a[i]);maxs[i%3]=Math.max(maxs[i%3],a[i]);}return {shape:m.metadata.vfxShape,vertices:m.getTotalVertices(),billboard:m.billboardMode,extent:mins.map((n,i)=>maxs[i]-n),texture:!!m.material?.diffuseTexture,position:m.position.asArray(),rotation:m.rotation.asArray()};})}},reset(hp=120,visible=true,clear=true){if(clear)library.setSkillMotion(actor,null);library.animate(actor,false,hp,false,false,.016,visible);return actor.getChildren().filter(n=>n.name.includes('motion-pivot')).map(n=>({position:n.position.asArray(),rotation:n.rotation.asArray()}))}};
