import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {Simulation} from '../src/simulation';
import {skills,type ClassId} from '../src/game/classes';
import {zoneMonsterGroups,WORLD_BOUNDS} from '../src/game/map-data';
const out='artifacts/lv20-vfx';
const jobs:ClassId[]=['swordsman','mage','archer'];
const fixture=`<!doctype html><html><body style="margin:0;background:#d2dfdc"><canvas style="width:100vw;height:100vh;display:block"></canvas><div id="label" style="position:absolute;top:12px;left:12px;font:18px sans-serif;color:#142722;background:#ffffffb0;padding:8px"></div><script type="module" src="/tests/lv10-vfx-fixture.ts"></script></body></html>`;
for(const job of jobs)test(`${job} Lv20: both branch impacts stay volumetric and bounded in low/high with live release video`,async({browser})=>{
 mkdirSync(out,{recursive:true});const context=await browser.newContext({viewport:{width:1000,height:720},recordVideo:{dir:out+'/raw',size:{width:1000,height:720}}}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>{errors.push(e.message);console.error('QA_PAGE_ERROR',e.message)});
 await page.route('**/lv20-review.html*',r=>r.fulfill({contentType:'text/html',body:fixture}));await page.goto(`/lv20-review.html?job=${job}`);await page.waitForFunction(()=>(window as any).review?.library.active===1 || (window as any).review?.library.errors>0,{},{timeout:90000});await page.evaluate(()=>{(window as any).review.cameraAt(.65);(window as any).review.camera.position.scaleInPlace(1.7)});const records:any[]=[];
 for(const low of [false,true]){await page.evaluate(low=>(window as any).review.quality(low),low);for(const skill of skills[job].filter(s=>s.level===20)){
  for(const age of [.08,.24,.49]){await page.evaluate(({id,age})=>(window as any).review.preview(id,age/.384),{id:skill.id,age});await page.locator('#label').evaluate((el,text)=>{el.textContent=text},skill.name+' · release '+Math.round(age*1000)+' ms');const d=await page.evaluate(()=>(window as any).review.describe());expect(d.modelErrors).toBe(0);expect(d.actorPosition).toEqual([0,0,0]);expect(d.vfx.active).toBeLessThanOrEqual(low?40:96);expect(d.vfx.pooled).toBeLessThanOrEqual(160);expect(d.shapes.length).toBeGreaterThan(0);expect(d.shapes.every((m:any)=>m.billboard===0&&!m.texture)).toBe(true);records.push({id:skill.id,low,age,...d});await page.screenshot({path:`${out}/${skill.id}-${low?'low':'high'}-${age}.png`});}
  await page.evaluate(id=>(window as any).review.play(id),skill.id);await page.waitForFunction(()=>(window as any).review.describe().vfx.active===0,{},{timeout:10000});
 }}
 expect(errors).toEqual([]);writeFileSync(`${out}/${job}-preview.json`,JSON.stringify({environment:'Chromium ANGLE SwiftShader; render-only frozen frames and continuous releases, no gameplay mutation',records,errors},null,2));const video=page.video();await context.close();if(video)await video.saveAs(`${out}/${job}-preview.webm`);
});
for(const job of jobs)for(const branch of [0,1])test(`${job} branch${branch} Lv20: learned skill genuinely damages enemies and VFX clears`,async({browser})=>{
 mkdirSync(out,{recursive:true});const skill=skills[job].find(s=>s.level===20&&s.branch===branch)!,seed=new Simulation(()=>.5,undefined,null);seed.save.job=job;seed.save.level=100;seed.save.hp=seed.maxHp;seed.save.mp=seed.maxMp;seed.save.tutorial=['skip'];seed.chooseSkill(`${job}-1`);seed.save.hotbar=Array(6).fill(null);
 const context=await browser.newContext({viewport:{width:1200,height:800},recordVideo:{dir:out+'/raw',size:{width:1200,height:800}}}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>{errors.push(e.message);console.error('QA_PAGE_ERROR',e.message)});await page.addInitScript(save=>{localStorage.setItem('mossvale-save',JSON.stringify(save));localStorage.setItem('mossvale-quality','low')},seed.save);const snap=()=>page.evaluate(()=>(window as any).mossvale.snapshot());
 await page.goto('/?practice=1');await expect(page.locator('#hp-text')).toContainText('/',{timeout:90000});await page.waitForFunction(()=>{const s=(window as any).mossvale?.snapshot();return s&&s.modelsExpected>0&&s.riggedActors===s.modelsExpected&&s.modelErrors===0},{},{timeout:90000});await page.keyboard.press('k');await page.locator(`[data-learn="${skill.id}"]`).click();await page.keyboard.press('Escape');expect((await snap()).hotbar[0]).toBe(skill.id);expect((await snap()).unlockedSkills).toContain(skill.id);
 const group=zoneMonsterGroups('glade')[0];await page.keyboard.press('m');const box=(await page.locator('#large-map').boundingBox())!;await page.mouse.click(box.x+(group.x-WORLD_BOUNDS.minX)/(WORLD_BOUNDS.maxX-WORLD_BOUNDS.minX)*box.width,box.y+(group.z-WORLD_BOUNDS.minZ)/(WORLD_BOUNDS.maxZ-WORLD_BOUNDS.minZ)*box.height);const request=(await snap()).destination;expect(request).not.toBeNull();await page.waitForFunction(({x,z})=>{const s=(window as any).mossvale.snapshot();return Math.hypot(s.x-x,s.z-z)<1},request,{timeout:60000});await page.keyboard.down('d');await page.waitForFunction(()=>(window as any).mossvale.snapshot().destination===null,{},{timeout:5000});await page.keyboard.up('d');await page.waitForFunction(id=>{const s=(window as any).mossvale.snapshot();return s.monsters.filter((m:any)=>m.groupId===id&&m.alive&&Math.hypot(m.x-s.x,m.z-s.z)<2.6).length>=4},group.id,{timeout:30000});
 // Pause with a real panel before casting to stop automatic basic swings while taking the baseline.
 await page.keyboard.press('k');const before=await snap();await page.keyboard.press('Escape');await page.keyboard.press('1');await page.waitForFunction(({id,kills})=>{const s=(window as any).mossvale.snapshot();return s.skillCooldowns[id]>0&&s.kills>kills},{id:skill.id,kills:before.kills},{timeout:10000});const after=await snap();expect(after.mp).toBeLessThan(before.mp);expect(after.skillCooldowns[skill.id]).toBeGreaterThan(0);expect(after.kills).toBeGreaterThan(before.kills);
 await page.screenshot({path:`${out}/${skill.id}-real-cast.png`});await page.locator('#untarget').evaluate((b:HTMLElement)=>b.click());await page.waitForFunction(()=>{const s=(window as any).mossvale.snapshot();return !s.skillMotion&&s.vfx.active===0},{},{timeout:10000});const recovered=await snap();expect(recovered.modelErrors).toBe(0);expect(errors).toEqual([]);
 writeFileSync(`${out}/${skill.id}-gameplay.json`,JSON.stringify({environment:'Chromium ANGLE SwiftShader; authentic learned Lv20 skill rank1; prerequisite learned; level100 hero fixture protects recording from deaths',before,after,recovered,errors},null,2));const video=page.video();await context.close();if(video)await video.saveAs(`${out}/${skill.id}-gameplay.webm`);
});
