import {test,expect} from '@playwright/test';
import {Simulation,type Item} from '../src/simulation';
import {equipment,gearById,rarityOrder,secondaryCounts,BAG_CAPACITY,itemBonuses} from '../src/game/equipment';
import {craftingMaterials,gearRecipe,craftCost,materialCount,materialKey,rollMaterialDrops} from '../src/game/crafting';
import {transact} from '../server/realm';
import {shareKill,community,communityCommand} from '../server/community';
function prepared(){const s=new Simulation(()=>.5,undefined,null);s.save.level=100;s.save.gold=100000;s.save.items=[];return s;}
function fill(s:Simulation){while(s.save.items.filter(i=>i.count>0).length<BAG_CAPACITY)s.save.items.push({name:'filler '+s.save.items.length,icon:'leaf',count:1});}
function memory(){let realm:any=null,revision=0;return {async read(){return realm?{realm:structuredClone(realm),revision}:null},async create(r:any){realm=structuredClone(r)},async commit(v:number,r:any){if(v!==revision)return false;realm=structuredClone(r);revision++;return true}};}
test('all equipment crafts every rarity from exact matching ingredients with rarity affixes and role primaries',()=>{
 for(const gear of equipment)for(const rarity of rarityOrder){const s=prepared();for(const [name,count] of gearRecipe(gear))s.addItem(name,'leaf',count,rarity);const gold=s.save.gold;expect(s.craft(gear.id,rarity)).toBe(true);const item=s.save.items.find(i=>i.gearId===gear.id)!;expect(item.rarity).toBe(rarity);expect(Object.keys(item.secondary!)).toHaveLength(secondaryCounts[rarity]);expect(s.save.gold).toBe(gold-craftCost(gear));expect(item.id).toBeTruthy();const keys=Object.keys(itemBonuses({...item,secondary:{}},false));if(gear.slot==='weapon'||gear.slot==='accessory')expect(keys).toContain('atk');else expect(keys.sort()).toEqual(['def','hp']);}
});
test('wrong rarity ingredients and invalid rarity cannot charge or destroy inventory',()=>{
 const s=prepared();for(const name of craftingMaterials)s.addItem(name,'leaf',100,'common');const before=structuredClone(s.save);expect(s.craft('starfall-blade','rare')).toBe(false);expect(s.save).toEqual(before);expect(s.craft('starfall-blade','invalid' as any)).toBe(false);expect(s.save).toEqual(before);
});
test('material stacks never pool across rarity; legacy duplicates merge without count loss and migration is idempotent',()=>{
 const s=prepared();s.save.items=[{name:'Shade essence',icon:'leaf',count:2},{name:'Shade essence',icon:'leaf',count:3},{name:'Shade essence',icon:'leaf',count:8,rarity:'rare'}];const loaded=new Simulation(()=>.5,s.save,null);expect(loaded.save.items).toHaveLength(2);expect(materialCount(loaded.save.items,'Shade essence','common')).toBe(5);expect(materialCount(loaded.save.items,'Shade essence','rare')).toBe(8);expect(new Set(loaded.save.items.map(i=>i.id)).size).toBe(2);expect(new Simulation(()=>.5,loaded.save,null).save.items).toEqual(loaded.save.items);expect(loaded.upgradeMaterial('Shade essence','common')).toBe(true);expect(materialCount(loaded.save.items,'Shade essence','rare')).toBe(9);
});
test('5 same material and rarity upgrade frees full-bag slots; overflow and Legend reject atomically',()=>{
 for(const name of craftingMaterials)for(const rarity of rarityOrder.slice(0,-1)){const s=prepared();s.addItem(name,'leaf',5,rarity);fill(s);expect(s.upgradeMaterial(name,rarity)).toBe(true);expect(s.save.items.filter(i=>i.count>0)).toHaveLength(BAG_CAPACITY);const next=rarityOrder[rarityOrder.indexOf(rarity)+1];expect(materialCount(s.save.items,name,next)).toBe(1);}
 const s=prepared();s.addItem('Rune stone','leaf',6,'epic');fill(s);const before=structuredClone(s.save);expect(s.upgradeMaterial('Rune stone','epic')).toBe(false);expect(s.upgradeMaterial('Rune stone','legend')).toBe(false);expect(s.save).toEqual(before);
});
test('craft full bag uses consumed stacks as slots and rejects when no stack can be freed',()=>{
 const s=prepared(),g=gearById('sprout-blade')!;for(const [name,count] of gearRecipe(g))s.addItem(name,'leaf',count);fill(s);expect(s.craft(g.id)).toBe(true);expect(s.save.items.filter(i=>i.count>0).length).toBe(BAG_CAPACITY-1);
 const full=prepared();for(const [name,count] of gearRecipe(g))full.addItem(name,'leaf',count+1);fill(full);const before=structuredClone(full.save);expect(full.craft(g.id)).toBe(false);expect(full.save).toEqual(before);
});
test('legacy gloves become Pants while unique ID, equipped reference, refinement and rarity survive',()=>{
 const s=prepared(),g=gearById('starfall-gloves')!;expect(g.slot).toBe('pants');expect(g.icon).toBe('starfall-pants');s.addItem(g.name,g.icon);const item=s.save.items[0];item.refine=8;item.rarity='epic';item.name='Starfall Gloves';item.icon='starfall-gloves';(s.save.equipped as any).gloves=item.id;s.save.equipped.pants=null;const loaded=new Simulation(()=>.5,s.save,null);expect(loaded.save.equipped.pants).toBe(item.id);expect((loaded.save.equipped as any).gloves).toBeUndefined();expect(loaded.save.items[0]).toMatchObject({id:item.id,refine:8,rarity:'epic',name:g.name,icon:'starfall-pants'});
});
test('all maps normal and boss material rolls include each ingredient and all four rarities',()=>{
 for(const boss of [false,true])for(let n=0;n<3;n++)for(const roll of [0,.8,.96,.999]){const values=[0,n/3+.01,roll];const drops=rollMaterialDrops(boss,()=>values.shift()!);expect(drops).toHaveLength(1);expect(drops[0].name).toBe(craftingMaterials[n]);expect(drops[0].count).toBe(boss?3:1);expect(rarityOrder).toContain(drops[0].rarity);}
 for(const zone of ['glade','marsh','orchard','frost','ruins'] as const){const s=prepared();s.populateZone(zone);s.random=()=>0;const m=s.monsters[0];const before=s.loot.length;s.hit(m,9999999);expect(s.loot.slice(before).some(l=>l.item&&craftingMaterials.includes(l.name)&&l.item.rarity)).toBe(true);}
});
test('server validates craft and upgrade rarity, deduplicates replay and spawns material rarity authoritatively',async()=>{
 const db=memory(),user={id:'a',name:'A',admin:true};let snap=await transact(db,user,{connect:true},1000);const row=(await db.read())!,save=row.realm.players.a.actor.save;save.level=100;save.gold=10000;for(const [name,count] of gearRecipe(gearById('starfall-blade')!))save.items.push({name,count,icon:'leaf',rarity:'epic',id:materialKey(name,'epic')});await db.commit(row.revision,row.realm);
 const command={id:snap.player.session.id+':1',type:'craft',args:['starfall-blade','epic']};snap=await transact(db,user,{commands:[command]},1000);const gold=snap.player.actor.save.gold;snap=await transact(db,user,{commands:[command]},1000);expect(snap.player.actor.save.gold).toBe(gold);expect(snap.player.actor.save.items.filter(i=>i.gearId==='starfall-weapon')).toHaveLength(1);
 await expect(transact(db,user,{commands:[{id:snap.player.session.id+':2',type:'craft',args:['starfall-blade','impossible']}]},1000)).rejects.toThrow('Invalid recipe rarity');
 snap=await transact(db,user,{commands:[{id:snap.player.session.id+':2',type:'adminSpawn',args:['material:Sky feather',5,'legend',0]}]},1000);expect(snap.player.actor.save.items.find(i=>i.name==='Sky feather')).toMatchObject({rarity:'legend',count:5,id:materialKey('Sky feather','legend')});
});
test('party rewards retain material rarity and count',async()=>{
 const db=memory();await transact(db,{id:'a',name:'A'},{connect:true},1000);await transact(db,{id:'b',name:'B'},{connect:true},1000);const row=(await db.read())!,r=row.realm;community(r).parties.push({id:'p',leader:'a',members:['a','b'],invites:[],lootCursor:0});const actors=['a','b'].map(id=>({p:r.players[id],sim:new Simulation(()=>0,r.players[id].actor.save,null)}));for(const a of actors){a.p.room='glade';a.sim.x=0;a.sim.z=0;}const m=actors[0].sim.monsters[0];m.x=0;m.z=0;expect(shareKill(r,actors[0].p,m,actors,1000)).toBe(true);const drops=actors.flatMap(a=>a.sim.save.items).filter(i=>i.name==='Shade essence');expect(drops).toHaveLength(1);expect(drops[0]).toMatchObject({rarity:'common',count:1,id:materialKey('Shade essence','common')});
});
test('market transfer preserves rarity and never merges another rarity stack',async()=>{
 const db=memory();await transact(db,{id:'a',name:'A'},{connect:true},1000);await transact(db,{id:'b',name:'B'},{connect:true},1000);const r=(await db.read())!.realm,a=r.players.a,b=r.players.b;a.actor.save.items.push({name:'Rune stone',icon:'leaf',count:5,rarity:'epic',id:materialKey('Rune stone','epic')});b.actor.save.items.push({name:'Rune stone',icon:'leaf',count:2,rarity:'rare',id:materialKey('Rune stone','rare')});communityCommand(r,a,'marketList',[materialKey('Rune stone','epic'),5,10],1000,'list');const listing=community(r).listings[0];communityCommand(r,b,'marketBuy',[listing.id],1000,'buy');expect(materialCount(b.actor.save.items,'Rune stone','epic')).toBe(5);expect(materialCount(b.actor.save.items,'Rune stone','rare')).toBe(2);
});

test('material upgrade server command consumes exactly five once on replay',async()=>{
 const db=memory(),user={id:'a',name:'A',admin:true};let snap=await transact(db,user,{connect:true},1000);snap=await transact(db,user,{commands:[{id:snap.player.session.id+':1',type:'adminSpawn',args:['material:Rune stone',5,'rare',0]}]},1000);const command={id:snap.player.session.id+':2',type:'upgradeMaterial',args:['Rune stone','rare']};snap=await transact(db,user,{commands:[command]},1000);snap=await transact(db,user,{commands:[command]},1000);expect(materialCount(snap.player.actor.save.items,'Rune stone','rare')).toBe(0);expect(materialCount(snap.player.actor.save.items,'Rune stone','epic')).toBe(1);
});
test('trade transfers exact material rarity and retains separate destination stacks',async()=>{
 const db=memory();await transact(db,{id:'a',name:'A'},{connect:true},1000);await transact(db,{id:'b',name:'B'},{connect:true},1000);const r=(await db.read())!.realm,a=r.players.a,b=r.players.b;for(const player of [a,b]){player.room='glade';player.actor.x=0;player.actor.z=0;}a.actor.save.items.push({name:'Sky feather',icon:'feather',count:5,rarity:'legend',id:materialKey('Sky feather','legend')});b.actor.save.items.push({name:'Sky feather',icon:'feather',count:2,rarity:'rare',id:materialKey('Sky feather','rare')});communityCommand(r,a,'tradeInvite',['b'],1000,'invite');const t=community(r).trades[0];communityCommand(r,b,'tradeAccept',[t.id],1000,'accept');communityCommand(r,a,'tradeOffer',[t.id,{item:materialKey('Sky feather','legend'),count:5,gold:0}],1000,'offer-a');communityCommand(r,b,'tradeOffer',[t.id,{item:'',count:0,gold:0}],1000,'offer-b');communityCommand(r,a,'tradeConfirm',[t.id],1000,'confirm-a');communityCommand(r,b,'tradeConfirm',[t.id],1000,'confirm-b');expect(materialCount(b.actor.save.items,'Sky feather','legend')).toBe(5);expect(materialCount(b.actor.save.items,'Sky feather','rare')).toBe(2);expect(materialCount(a.actor.save.items,'Sky feather','legend')).toBe(0);
});
