import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {Simulation} from '../src/simulation';
const out='artifacts/mesh-characters';
const jobs=['swordsman','mage','archer'] as const;
const motions=['idle','walk','run','attack','attack-heavy','skill','skill-heal','skill-guard','skill-ultimate','hurt','death'];
function glb(path:string){const b=readFileSync(path);expect(b.subarray(0,4).toString()).toBe('glTF');expect(b.readUInt32LE(8)).toBe(b.length);return JSON.parse(b.subarray(20,20+b.readUInt32LE(12)).toString().trim());}
test('three final character GLBs have authored geometry, skins, texture and eleven motion aliases',()=>{
 const manifest=JSON.parse(readFileSync('public/models/manifest.json','utf8'));expect(readFileSync('art/characters-mesh/kaykit/LICENSE.txt','utf8')).toMatch(/CC0|Creative Commons Zero/i);
 for(const job of jobs){const entry=manifest[job];expect(entry.sourceCommit).toBe('672074b73ba276876a19e8816ecdc5241817ab47');expect(entry.sourceFile).toBe({swordsman:'Knight.glb',mage:'Mage.glb',archer:'Rogue.glb'}[job]);const source=glb(`art/characters-mesh/kaykit/source/${entry.sourceFile}`);expect(source.animations).toHaveLength(76);expect(createHash('sha256').update(readFileSync(`art/characters-mesh/kaykit/source/${entry.sourceFile}`)).digest('hex')).toBe(entry.sourceSha256);for(const clip of Object.values(entry.motionAliases))expect(source.animations.some((a:any)=>a.name===clip)).toBe(true);const g=glb(`public/models/${job}.glb`);expect(g.skins.length).toBeGreaterThan(0);expect(g.skins[0].joints.length).toBeGreaterThan(20);expect(g.meshes.length).toBeGreaterThan(3);expect(g.images.length).toBeGreaterThan(0);expect(g.textures.length).toBeGreaterThan(0);expect(g.animations.map((a:any)=>a.name).sort()).toEqual([...motions].sort());for(const a of g.animations)expect(a.channels.length).toBeGreaterThan(10);}
});
const fixture=`<!doctype html><html><body style="margin:0;background:#c7d9df"><canvas id="review" style="width:100vw;height:100vh;display:block"></canvas><script type="module" src="/tests/mesh-character-fixture.ts"></script></body></html>`;
for(const job of jobs)test(`${job}: actual Babylon mesh front/side low/high and motion samples`,async({browser})=>{
 mkdirSync(out,{recursive:true});const context=await browser.newContext({viewport:{width:900,height:900},recordVideo:{dir:out+'/video',size:{width:900,height:900}}});const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>{errors.push(e.message);console.log('QA_PAGE_ERROR',e.message)});await page.route('**/mesh-review.html*',r=>r.fulfill({contentType:'text/html',body:fixture}));await page.goto(`/mesh-review.html?job=${job}`);await page.waitForFunction(()=>(window as any).review?.library.active===1,{},{timeout:45000});
 const initial=await page.evaluate(()=>(window as any).review.describe());expect(initial.errors).toBe(0);expect(initial.clips).toHaveLength(11);const manifest=JSON.parse(readFileSync('public/models/manifest.json','utf8'))[job];expect(initial.meshes).toHaveLength(manifest.renderMeshes);for(const prop of manifest.props)expect(initial.meshes.some((m:any)=>m.name.includes(prop))).toBe(true);const weapons=initial.meshes.filter((m:any)=>/1H_|2H_|Shield/.test(m.name));expect(weapons).toHaveLength(job==='swordsman'?2:1);expect(initial.meshes.every((m:any)=>m.normals>0&&m.texture)).toBe(true);
 for(const low of [false,true]){await page.evaluate(low=>{const r=(window as any).review;r.library.setLowQuality(low);r.scene.shadowsEnabled=!low},low);for(const side of [false,true]){await page.evaluate(side=>{const r=(window as any).review;r.camera.position=new r.Vector3(side?4:0,1.25,side?0:4);r.camera.setTarget(new r.Vector3(0,.9,0))},side);await page.waitForTimeout(350);await page.screenshot({path:`${out}/${job}-${low?'low':'high'}-${side?'side':'front'}.png`});}const d=await page.evaluate(()=>(window as any).review.describe());expect(d.meshes.every((m:any)=>m.texture)).toBe(true);if(low)expect(d.meshes.every((m:any)=>m.material==='PBRMaterial'&&m.maxSimultaneousLights<=2&&!m.reflectionTexture&&!m.bumpTexture)).toBe(true);}
 await page.evaluate(()=>{const r=(window as any).review;r.camera.position=new r.Vector3(2,1.4,4);r.camera.setTarget(new r.Vector3(0,.9,0));r.library.setLowQuality(false);r.scene.shadowsEnabled=true});
 const samples:any[]=[];for(const motion of ['idle','walk','attack','skill','hurt','death']){await page.evaluate(motion=>{const r=(window as any).review;r.scene.animationGroups.forEach(g=>g.stop());const g=r.scene.animationGroups.find(g=>g.name.endsWith('-'+motion)||g.name===motion);g.start(motion==='idle'||motion==='walk')},motion);for(const delay of [100,250,450]){await page.waitForTimeout(delay);samples.push({motion,elapsedDelay:delay,...await page.evaluate(()=>(window as any).review.describe())});}if(motion==='death'){await page.waitForTimeout(1600);samples.push({motion,elapsedDelay:1600,tail:true,...await page.evaluate(()=>(window as any).review.describe())});}await page.screenshot({path:`${out}/${job}-motion-${motion}.png`});}
 for(const motion of ['walk','attack','skill','hurt','death']){const frames=samples.filter(s=>s.motion===motion);expect(JSON.stringify(frames[0].bones)).not.toBe(JSON.stringify(frames[2].bones));}expect(errors).toEqual([]);writeFileSync(`${out}/${job}-render.json`,JSON.stringify({environment:'Headless Chromium ANGLE SwiftShader software rendering; sampled poses, not all animation frames',initial,samples,errors},null,2));const video=page.video();await context.close();if(video)await video.saveAs(`${out}/${job}-motions.webm`);
});
for(const job of jobs)for(const quality of ['low','high'])test(`${job} ${quality}: loaded gameplay desktop/mobile and genuine movement`,async({page})=>{
 mkdirSync(out,{recursive:true});const sim=new Simulation(()=>.5,undefined,null);sim.save.job=job;sim.save.level=100;sim.save.hp=sim.maxHp;sim.save.mp=sim.maxMp;for(let n=1;n<=10;n++)sim.chooseSkill(`${job}-${n}`);sim.assignSkill(0,`${job}-10`);
 await page.addInitScript(({save,quality})=>{localStorage.setItem('mossvale-save',JSON.stringify(save));localStorage.setItem('mossvale-quality',quality)},{save:sim.save,quality});const errors:string[]=[];page.on('pageerror',e=>{errors.push(e.message);console.log('QA_PAGE_ERROR',e.message)});await page.setViewportSize({width:1200,height:800});await page.goto('/?practice=1');await page.waitForFunction(()=>{const s=(window as any).mossvale?.snapshot();return s&&s.drawCalls>0&&s.riggedActors>=s.monsters.length+3},{},{timeout:45000});const state=()=>page.evaluate(()=>(window as any).mossvale.snapshot());expect((await state()).modelErrors).toBe(0);await page.screenshot({path:`${out}/${job}-${quality}-gameplay-1200x800.png`});const before=await state();await page.keyboard.down('d');await page.waitForFunction(x=>(window as any).mossvale.snapshot().x>x+.5,before.x,{timeout:15000});await page.keyboard.up('d');await page.keyboard.press('Tab');const target=(await state()).target;expect(target).not.toBeNull();await page.setViewportSize({width:390,height:844});await page.screenshot({path:`${out}/${job}-${quality}-gameplay-390x844.png`});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);const after=await state();expect(after.modelErrors).toBe(0);expect(after.job).toBe(job);expect(after.items).toEqual(before.items);expect(errors).toEqual([]);writeFileSync(`${out}/${job}-${quality}-gameplay.json`,JSON.stringify({before,after,errors,selectedTarget:target,movementVerified:true,targetSelectionVerified:true},null,2));
});
test('mage: genuine learned cast consumes MP, cooldown and resolves',async({page})=>{
 const sim=new Simulation(()=>.5,undefined,null);sim.save.job='mage';sim.save.level=100;sim.save.hp=sim.maxHp;sim.save.mp=sim.maxMp;for(let n=1;n<=10;n++)sim.chooseSkill(`mage-${n}`);sim.assignSkill(0,'mage-10');await page.addInitScript(save=>{localStorage.setItem('mossvale-save',JSON.stringify(save));localStorage.setItem('mossvale-quality','low')},sim.save);const errors:string[]=[];page.on('pageerror',e=>{errors.push(e.message);console.log('QA_PAGE_ERROR',e.message)});await page.goto('/?practice=1');await page.waitForFunction(()=>{const s=(window as any).mossvale?.snapshot();return s&&s.riggedActors>=s.monsters.length+3},{},{timeout:45000});await page.keyboard.press('Tab');const before=await page.evaluate(()=>(window as any).mossvale.snapshot());await page.keyboard.press('1');await page.waitForFunction(()=>!!(window as any).mossvale.snapshot().cast,{},{timeout:15000});const casting=await page.evaluate(()=>(window as any).mossvale.snapshot());expect(casting.cast.skillId).toBe('mage-10');expect(casting.mp).toBeLessThan(before.mp);expect(casting.skillCooldowns['mage-10']).toBeGreaterThan(0);await page.screenshot({path:`${out}/mage-real-cast.png`});await page.waitForFunction(()=>!(window as any).mossvale.snapshot().cast,{},{timeout:15000});const after=await page.evaluate(()=>(window as any).mossvale.snapshot());expect(after.modelErrors).toBe(0);const hitBefore=before.monsters.find((m:any)=>m.id===casting.cast.targetId);const hitAfter=after.monsters.find((m:any)=>m.id===casting.cast.targetId);expect(after.kills>before.kills||!!(hitBefore&&hitAfter&&hitAfter.hp<hitBefore.hp)).toBe(true);expect(errors).toEqual([]);writeFileSync(`${out}/mage-real-cast.json`,JSON.stringify({before,casting,after,errors},null,2));
});
