import {test,expect} from '@playwright/test';
import {mkdirSync} from 'node:fs';
const origin='http://127.0.0.1:4173';
test('production PWA has valid manifest, real fullscreen controls, service worker and private API bypass',async({page,context})=>{
 let statusRequests=0;await page.route('**/api/auth/status',route=>{statusRequests++;return route.fulfill({json:{account:null},headers:{'Cache-Control':'no-store'}})});
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await expect(page.locator('#account-form')).toBeVisible();await expect(page.locator('#game')).toHaveCount(0);
 const manifest=await(await page.request.get(origin+'/manifest.webmanifest')).json();expect(manifest.id).toBe('/');expect(manifest.start_url).toBe('/');expect(manifest.scope).toBe('/');expect(manifest.display).toBe('fullscreen');expect(manifest.icons.some((i:any)=>i.purpose==='maskable'&&i.sizes==='512x512')).toBe(true);
 const cdp=await context.newCDPSession(page);const info=await cdp.send('Page.getAppManifest');expect(info.errors).toEqual([]);expect(info.url).toContain('/manifest.webmanifest');
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await expect(page.locator('#account-form')).toBeVisible();await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBe(true);expect(statusRequests).toBeGreaterThanOrEqual(2);
 await page.getByRole('button',{name:'Enter fullscreen',exact:true}).click();await expect.poll(()=>page.evaluate(()=>Boolean(document.fullscreenElement))).toBe(true);await expect(page.getByRole('button',{name:'Exit fullscreen',exact:true})).toBeVisible();await page.getByRole('button',{name:'Exit fullscreen',exact:true}).click();await expect.poll(()=>page.evaluate(()=>Boolean(document.fullscreenElement))).toBe(false);
 // Chromium's native install window cannot be accepted headlessly. Validate event plumbing separately from the real manifest/worker.
 await page.evaluate(()=>{const event=new Event('beforeinstallprompt');Object.assign(event,{prompt:async()=>{(window as any).__prompted=true},userChoice:Promise.resolve({outcome:'accepted'})});window.dispatchEvent(event)});await page.getByRole('button',{name:'Install Mossvale',exact:true}).click();expect(await page.evaluate(()=>(window as any).__prompted)).toBe(true);await expect(page.locator('[data-pwa-message]')).toContainText('Installation requested');
 mkdirSync('artifacts/pwa',{recursive:true});await page.screenshot({path:'artifacts/pwa/login-desktop.png'});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:'artifacts/pwa/login-mobile.png'});
 const cached=await page.evaluate(async()=>{const keys=await caches.keys(),urls:string[]=[];for(const key of keys)for(const r of await(await caches.open(key)).keys())urls.push(r.url);return urls});expect(cached.some(url=>new URL(url).pathname.startsWith('/api'))).toBe(false);expect(cached.some(url=>new URL(url).pathname==='/offline.html')).toBe(true);
 await context.setOffline(true);await page.reload();await expect(page.locator('body')).toContainText(/offline|connection|internet/i);await expect(page.locator('#game')).toHaveCount(0);await page.screenshot({path:'artifacts/pwa/offline.png'});await context.setOffline(false);await page.reload();await expect(page.locator('#account-form')).toBeVisible();expect(errors).toEqual([]);
});
test('iPhone receives Safari home screen instructions without a browser install event',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'});try{const page=await context.newPage();await page.route('**/api/auth/status',r=>r.fulfill({json:{account:null}}));await page.goto(origin);await page.getByRole('button',{name:'Add to Home Screen',exact:true}).click();await expect(page.locator('[data-pwa-message]')).toContainText('In Safari, tap Share');await expect(page.locator('#game')).toHaveCount(0);}finally{await context.close()}
});
test('practice game enters and exits actual fullscreen through Settings and canvas fits viewport',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('mossvale-quality','low'));const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/?practice=1');await expect(page.locator('#game')).toHaveCount(0);await page.locator('#practice-start').click();await expect(page.locator('#hp-text')).toContainText('/',{timeout:90000});await page.waitForFunction(()=>{const s=(window as any).mossvale?.snapshot();return s&&s.modelsExpected>0&&s.riggedActors===s.modelsExpected&&s.modelErrors===0},null,{timeout:90000});await page.locator('[data-panel="settings"]').first().click();await page.getByRole('button',{name:'Enter fullscreen',exact:true}).click();await expect.poll(()=>page.evaluate(()=>Boolean(document.fullscreenElement))).toBe(true);const fits=await page.evaluate(()=>{const r=document.querySelector('#game')!.getBoundingClientRect();return Math.abs(r.width-innerWidth)<2&&Math.abs(r.height-innerHeight)<2});expect(fits).toBe(true);await page.screenshot({path:'artifacts/pwa/game-fullscreen.png'});await page.getByRole('button',{name:'Exit fullscreen',exact:true}).click();await expect.poll(()=>page.evaluate(()=>Boolean(document.fullscreenElement))).toBe(false);await page.locator('#close-panel').click();await expect(page.locator('#hp-text')).toContainText('/');expect(errors).toEqual([]);
});
