import {test,expect} from '@playwright/test';
import {createClient,type Client} from '@libsql/client';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {initializeDatabase,libsqlDatabase} from '../server/libsql-database';
import {RealtimeRealm} from '../server/realtime-realm';
import {signTicket,verifyTicket,type TicketClaims} from '../server/realtime-ticket';
import {D1RealmStore} from '../server/store';
const secret='realtime-test-secret-only-at-least-32-characters';
let directory:string,client:Client,realm:RealtimeRealm;
test.beforeEach(async()=>{directory=await mkdtemp(join(tmpdir(),'realm-ws-'));client=createClient({url:'file:'+join(directory,'test.sqlite')});await initializeDatabase(client);realm=new RealtimeRealm(client);await realm.start();});
test.afterEach(async()=>{await realm.close().catch(()=>{});client.close();await rm(directory,{recursive:true,force:true});});
function claims():TicketClaims{const now=Date.now();return {version:1,realm:'glade-01',accountId:'a'.repeat(64),playerId:'account:test',name:'tester',admin:false,origin:'http://localhost:5173',sessionHash:'b'.repeat(64),issuedAt:now,expiresAt:now+60000,jti:crypto.randomUUID()};}
test('ticket signature, expiry and tampering are checked',async()=>{const data=claims(),ticket=await signTicket(data,secret);expect((await verifyTicket(ticket,secret)).playerId).toBe(data.playerId);await expect(verifyTicket(ticket+'x',secret)).rejects.toThrow();await expect(verifyTicket(await signTicket({...data,expiresAt:Date.now()-1},secret),secret)).rejects.toThrow();});
test('single owner and HTTP revision fence prevent parallel writers',async()=>{const second=new RealtimeRealm(client);await expect(second.start()).rejects.toThrow('Another persistent realm');const store=new D1RealmStore(libsqlDatabase(client)),state=await store.read();expect(state).toBeTruthy();expect(await store.commit(state!.revision,state!.realm)).toBe(false);});
test('movement advances in memory while checkpoint is delayed; durable acknowledgment follows save',async()=>{const first=await realm.connect(claims());await realm.checkpoint();const start=first.snapshot.player.actor.x;await realm.input('account:test',1,[1,0],[]);const original=client.transaction.bind(client);let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);let delayed=true;client.transaction=(async(...args:Parameters<Client['transaction']>)=>{if(delayed){delayed=false;await gate;}return original(...args);}) as Client['transaction'];const saving=realm.checkpoint();const now=Date.now();for(let i=1;i<=10;i++)realm.tick(now+i*50);expect(realm.snapshot('account:test').snapshot.player.actor.x).toBeGreaterThan(start+1);release();await saving;expect(realm.ready).toBe(true);});
test('checkpoint and restart retain character and resume deduplicated command sequence',async()=>{const data=claims(),first=await realm.connect(data);const session=first.snapshot.player.session.id;await realm.input(data.playerId,1,[0,0],[{id:session+':1',type:'buy',args:['Red potion']} as any]);await realm.checkpoint();expect(realm.snapshot(data.playerId).durableCommandSequence).toBe(1);await realm.close();realm=new RealtimeRealm(client);await realm.start();const resumed=await realm.connect(data,session);expect(resumed.durableCommandSequence).toBe(1);expect(resumed.snapshot.player.actor.save.gold).toBe(first.snapshot.player.actor.save.gold-15);await realm.input(data.playerId,1,[0,0],[{id:session+':1',type:'buy',args:['Red potion']} as any]);expect(realm.snapshot(data.playerId).snapshot.player.session.sequence).toBe(1);expect(realm.snapshot(data.playerId).snapshot.player.actor.save.gold).toBe(first.snapshot.player.actor.save.gold-15);});
test('economic command ack stays pending until durable commit and persistence failure freezes realm',async()=>{const data=claims(),first=await realm.connect(data);await realm.checkpoint();const original=client.transaction.bind(client);let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);client.transaction=(async(...args:Parameters<Client['transaction']>)=>{await gate;return original(...args);}) as Client['transaction'];await realm.input(data.playerId,1,[0,0],[{id:first.snapshot.player.session.id+':1',type:'sell',args:[]}]);expect(realm.snapshot(data.playerId).durableCommandSequence).toBe(0);release();await realm.checkpoint();expect(realm.snapshot(data.playerId).durableCommandSequence).toBe(1);client.transaction=(async()=>{throw new Error('database unavailable');}) as Client['transaction'];await expect(realm.checkpoint()).rejects.toThrow();expect(realm.ready).toBe(false);await expect(realm.input(data.playerId,2,[1,0],[])).rejects.toThrow();});
