import {test,expect} from '@playwright/test';
import {createClient,type Client} from '@libsql/client';
import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {initializeDatabase,libsqlDatabase} from '../server/libsql-database';
import {D1RealmStore} from '../server/store';import {transact} from '../server/realm';
import {RealtimeRealm} from '../server/realtime-realm';import {species} from '../src/game/content';
import type {TicketClaims} from '../server/realtime-ticket';
let client:Client,directory:string,realm:RealtimeRealm|undefined;
const identity={id:'account:loot-test',name:'loot_tester'};
function claims():TicketClaims{return{version:1,realm:'glade-01',accountId:'a'.repeat(64),playerId:identity.id,name:identity.name,admin:false,origin:'https://rush-mania.vercel.app',sessionHash:'b'.repeat(64),issuedAt:Date.now(),expiresAt:Date.now()+60000,jti:crypto.randomUUID()};}
test.beforeEach(async()=>{directory=await mkdtemp(join(tmpdir(),'realtime-loot-'));client=createClient({url:'file:'+join(directory,'game.sqlite')});await initializeDatabase(client);});
test.afterEach(async()=>{await realm?.close().catch(()=>{});realm=undefined;client.close();await rm(directory,{recursive:true,force:true});});
test('realtime boss kill drops exactly two gear pieces; collection survives checkpoint and restart',async()=>{const store=new D1RealmStore(libsqlDatabase(client)),first=await transact(store,identity,{connect:true});const row=(await store.read())!,player=row.realm.players[identity.id],boss=row.realm.rooms!.glade.monsters.find(m=>species[m.kind].boss)!;expect(boss).toBeTruthy();player.actor.x=boss.x-1;player.actor.z=boss.z;player.actor.target=boss.id;player.actor.attackTimer=0;boss.hp=1;row.realm.time=Date.now();await store.commit(row.revision,row.realm);realm=new RealtimeRealm(client);await realm.start();const resumed=await realm.connect(claims(),first.player.session.id);await realm.input(identity.id,1,[0,0],[{id:first.player.session.id+':1',type:'select',args:[boss.id]}]);realm.tick(Date.now()+50);const killed=realm.snapshot(identity.id).snapshot;expect(killed.player.actor.save.kills).toBe(resumed.snapshot.player.actor.save.kills+1);const gears=killed.player.actor.loot.filter(l=>l.item?.gearId);expect(gears).toHaveLength(2);const ids=gears.map(l=>l.item!.id);await realm.input(identity.id,2,[0,0],[{id:first.player.session.id+':2',type:'collect',args:[]}]);await realm.checkpoint();const collected=realm.snapshot(identity.id);expect(collected.durableCommandSequence).toBe(2);expect(collected.snapshot.player.actor.loot).toHaveLength(0);expect(ids.every(id=>collected.snapshot.player.actor.save.items.some(i=>i.id===id))).toBe(true);await realm.close();realm=new RealtimeRealm(client);await realm.start();const reopened=await realm.connect(claims(),first.player.session.id);expect(ids.every(id=>reopened.snapshot.player.actor.save.items.some(i=>i.id===id))).toBe(true);});
test('pre-WebSocket ground loot can be collected once through resumed realtime session',async()=>{const store=new D1RealmStore(libsqlDatabase(client)),first=await transact(store,identity,{connect:true});const row=(await store.read())!,actor=row.realm.players[identity.id].actor;actor.loot=[{x:actor.x,z:actor.z,name:'Red potion',icon:'health-potion'}];const before=actor.save.items.find(i=>i.name==='Red potion')!.count;await store.commit(row.revision,row.realm);realm=new RealtimeRealm(client);await realm.start();await realm.connect(claims(),first.player.session.id);const command={id:first.player.session.id+':1',type:'collect',args:[]};await realm.input(identity.id,1,[0,0],[command]);await realm.checkpoint();await realm.input(identity.id,2,[0,0],[command]);const current=realm.snapshot(identity.id).snapshot.player.actor;expect(current.loot).toHaveLength(0);expect(current.save.items.find(i=>i.name==='Red potion')!.count).toBe(before+1);});
