import {test,expect} from '@playwright/test';
import {Simulation} from '../src/simulation';
import {skills,classes,type ClassId} from '../src/game/classes';
import {transact} from '../server/realm';
const fresh=()=>new Simulation(()=>.5,undefined,null);
test('60 skills cover ten alternatives per path, choices require level and previous stage and permit mixing',()=>{
 for(const job of Object.keys(classes) as ClassId[]){expect(skills[job]).toHaveLength(20);for(const branch of [0,1])expect(skills[job].filter(s=>s.branch===branch).map(s=>s.stage)).toEqual([1,2,3,4,5,6,7,8,9,10]);const sim=fresh();sim.setClass(job);expect(sim.save.hotbar).toHaveLength(6);expect(sim.save.auxiliary).toHaveLength(4);expect(sim.chooseSkill(job+'-1')).toBe(false);sim.save.level=100;expect(sim.chooseSkill(job+'-2')).toBe(false);for(let n=1;n<=10;n++){const id=n%2?job+'-'+n:job+'-b-'+n;expect(sim.chooseSkill(id)).toBe(true);expect(sim.chooseSkill(n%2?job+'-b-'+n:job+'-'+n)).toBe(false);}expect(sim.unlockedSkills).toHaveLength(10);expect(sim.assignSkill(5,sim.unlockedSkills[9].id)).toBe(true);expect(sim.assignSkill(0,job+'-b-1')).toBe(false);expect(sim.castSkill(job+'-b-1')).toBe(false);expect(sim.assignSkill(6,job+'-1')).toBe(false);}
});
test('skill and auxiliary slots reject cross-category drops, share potion cooldown and do not consume at full health',()=>{
 const sim=fresh();sim.save.level=100;sim.chooseSkill('swordsman-1');expect(sim.assignSkill(0,'Red potion')).toBe(false);expect(sim.assignAuxiliary(0,'swordsman-1')).toBe(false);expect(sim.assignAuxiliary(0,'Common refine stone')).toBe(false);expect(sim.assignAuxiliary(4,'Red potion')).toBe(false);expect(sim.assignAuxiliary(3,'Red potion')).toBe(true);expect(sim.save.auxiliary[0]).toBeNull();expect(sim.assignAuxiliary(2,'Blue potion')).toBe(true);sim.save.hp=sim.maxHp;expect(sim.useAuxiliary(3)).toBe(false);const red=sim.save.items[0].count,blue=sim.save.items[1].count;sim.save.hp=1;sim.save.mp=0;expect(sim.useAuxiliary(3)).toBe(true);expect(sim.save.items[0].count).toBe(red-1);expect(sim.useAuxiliary(2)).toBe(false);expect(sim.save.items[1].count).toBe(blue);sim.populateZone('town');sim.tick(2.1,0,0);expect(sim.useAuxiliary(2)).toBe(true);expect(sim.save.items[1].count).toBe(blue-1);
});
test('legacy builds migrate to six skills and four item slots while v7 choices and per-class progression persist',()=>{
 const sim=fresh();const old=structuredClone(sim.save);old.version=6;old.level=100;old.gold=888;old.hotbar=['swordsman-1','swordsman-2','swordsman-7','swordsman-10'];const migrated=new Simulation(()=>.5,old,null);expect(migrated.save.version).toBe(7);expect(migrated.save.gold).toBe(888);expect(migrated.save.hotbar).toEqual([...old.hotbar,null,null]);expect(migrated.unlockedSkills).toHaveLength(10);expect(migrated.resetSkills()).toBe(true);expect(migrated.chooseSkill('swordsman-b-1')).toBe(true);migrated.setClass('mage');migrated.setClass('swordsman');expect(migrated.unlockedSkills.map(k=>k.id)).toEqual(['swordsman-b-1']);expect(new Simulation(()=>.5,migrated.save,null).save.skillChoices).toEqual(migrated.save.skillChoices);migrated.skillCooldowns['swordsman-b-1']=8;expect(migrated.resetSkills()).toBe(false);expect(migrated.save.skillChoices.swordsman[0]).toBe('swordsman-b-1');
});
test('server enforces choices and slot categories, persists choices and retries a consumable command exactly once',async()=>{
 let realm:any=null,revision=0;const store={async read(){return realm?{realm:structuredClone(realm),revision}:null},async create(r:any){realm=structuredClone(r)},async commit(v:number,r:any){if(v!==revision)return false;realm=structuredClone(r);revision++;return true}};const user={id:'paths',name:'Hero'};let s=await transact(store,user,{connect:true},1000);realm.players.paths.actor.save.level=100;realm.players.paths.actor.save.hp=1;realm.players.paths.actor.save.mp=0;
 const send=async(type:string,args:any[])=>{s=await transact(store,user,{commands:[{id:s.player.session.id+':'+(s.player.session.sequence+1),type,args}]},1000);return s};await send('chooseSkill',['swordsman-b-1']);await send('chooseSkill',['swordsman-1']);expect(s.player.actor.save.skillChoices.swordsman[0]).toBe('swordsman-b-1');await send('assignSkill',[5,'Red potion']);expect(s.player.actor.save.hotbar[5]).toBeNull();await send('assignAuxiliary',[2,'swordsman-b-1']);expect(s.player.actor.save.auxiliary[2]).toBeNull();await send('assignSkill',[5,'swordsman-b-1']);expect(s.player.actor.save.hotbar[5]).toBe('swordsman-b-1');const command={id:s.player.session.id+':'+(s.player.session.sequence+1),type:'useAuxiliary',args:[0]};await transact(store,user,{commands:[command]},1000);s=await transact(store,user,{commands:[command]},1000);expect(s.player.actor.save.items.find(i=>i.name==='Red potion')!.count).toBe(7);expect(s.player.actor.auxiliaryCooldown).toBe(2);expect(s.player.actor.cooldowns).toHaveLength(10);await expect(send('skill',[6])).rejects.toMatchObject({status:400});
});
