import {test,expect} from '@playwright/test';
import {Simulation} from '../src/simulation';
const seed=()=>{const sim=new Simulation(()=>.5,undefined,null);sim.save.level=100;sim.save.hp=sim.maxHp;sim.addItem('Dew jelly','jelly');return sim.save};
test('new builds choose one path at each stage, populate six skills, assign auxiliary items, and persist across reload',async({page})=>{
 page.setDefaultTimeout(10000);await page.setViewportSize({width:1200,height:800});await page.addInitScript(save=>{if(!localStorage.getItem('mossvale-save'))localStorage.setItem('mossvale-save',JSON.stringify(save));localStorage.setItem('mossvale-quality','low')},seed());const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?practice=1');await expect(page.locator('#hp-text')).toContainText('/');await expect(page.locator('.action-bar [data-skill]')).toHaveCount(6);await expect(page.locator('.action-bar [data-aux]')).toHaveCount(4);await page.keyboard.press('k');await expect(page.locator('.skill-card')).toHaveCount(20);await expect(page.locator('.skill-stage')).toHaveCount(10);await expect(page.locator('[data-learn="swordsman-2"]')).toBeDisabled();
 for(let n=1;n<=10;n++){await page.locator(`[data-learn="swordsman-${n%2?'':'b-'}${n}"]`).click();}await expect(page.locator('.learned-tag')).toHaveCount(10);await expect(page.locator('[data-learn="swordsman-b-1"]')).toBeDisabled();await expect(page.locator('.loadout-slot')).toHaveCount(6);await page.locator('.panel-body').evaluate(e=>e.scrollTop=0);await page.screenshot({path:'artifacts/skill-paths-1200.png'});
 await page.locator('[data-skill-id="swordsman-9"]').dragTo(page.locator('.action-bar [data-hotbar="5"]'),{sourcePosition:{x:10,y:10}});await expect(page.locator('.loadout-slot[data-hotbar="5"]')).toContainText('Earthbreaker');await page.locator('#auxiliary-3-trigger').click();await page.getByRole('option',{name:/Red potion/}).click();await expect.poll(()=>page.evaluate(()=>(window as any).mossvale.snapshot().auxiliary[3])).toBe('Red potion');await page.keyboard.press('Escape');await page.keyboard.press('i');await page.locator('.inventory-grid [data-item="Blue potion"]').dragTo(page.locator('.action-bar [data-aux="2"]'));await expect.poll(()=>page.evaluate(()=>(window as any).mossvale.snapshot().auxiliary[2])).toBe('Blue potion');await page.keyboard.press('Escape');await page.screenshot({path:'artifacts/hotbar-six-four.png'});
 const b=await page.locator('.bottom-center').boundingBox();expect(b!.x).toBeGreaterThanOrEqual(0);expect(b!.x+b!.width).toBeLessThanOrEqual(1200);expect(b!.y+b!.height).toBeLessThanOrEqual(800);await page.reload();await expect(page.locator('#hp-text')).toContainText('/');const state=await page.evaluate(()=>(window as any).mossvale.snapshot());expect(state.skillChoices.swordsman.filter(Boolean)).toHaveLength(10);expect(state.hotbar[5]).toBe('swordsman-9');expect(state.auxiliary[2]).toBe('Blue potion');expect(errors).toEqual([]);
});
test('mobile tree, six skill keys and four auxiliary keys fit without overflow and can learn and reset',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.addInitScript(save=>{localStorage.setItem('mossvale-save',JSON.stringify(save));localStorage.setItem('mossvale-quality','low')},seed());await page.goto('/?practice=1');await expect(page.locator('#hp-text')).toContainText('/');for(const selector of ['.skill-hotbar','.aux-hotbar','.bottom-center']){const box=(await page.locator(selector).boundingBox())!;expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(390);}await page.locator('[data-panel="skills"]').click();await page.locator('[data-learn="swordsman-b-1"]').click();await expect(page.locator('.loadout-slot[data-hotbar="0"]')).toContainText('Bulwark');expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:'artifacts/skill-paths-mobile.png'});await page.locator('#reset-skills').click();await expect(page.locator('.learned-tag')).toHaveCount(0);await expect(page.locator('[data-learn="swordsman-1"]')).toBeEnabled();
});
