import {test,expect} from '@playwright/test';
import {Simulation} from '../src/simulation';
import {classes,skills,skillAtRank,type ClassId} from '../src/game/classes';
import {skillRankConfig} from '../src/config/balance';
import {transact} from '../server/realm';
import type {Realm} from '../server/protocol';
import type {RealmStore} from '../server/store';
function fresh(level=100){const s=new Simulation(()=>.5,undefined,null);s.save.level=level;s.save.mp=s.maxMp;s.monsters=[];s.obstacles=[];return s;}
function learn(s:Simulation,id:string){const stage=skills[s.save.job].find(k=>k.id===id)!.stage;for(let n=1;n<stage;n++)s.chooseSkill(`${s.save.job}-${n}`);expect(s.chooseSkill(id)).toBe(true);}
function enemies(s:Simulation,count=12){s.populateZone('glade');s.obstacles=[];const base=s.monsters[0];s.monsters=Array.from({length:count},(_,n)=>({...structuredClone(base),id:n,x:1+(n%3)*.3,z:Math.floor(n/3)*.2,homeX:1,homeZ:0,hp:1e7,stun:0,slow:0,poison:0,alive:true}));s.x=0;s.z=0;s.target=0;s.attackTimer=100;s.balance[base.kind]={hp:1e7,defense:0,atk:1};}
test('all60skills and50rankcells follow damage/target tables and retain their identities',()=>{
 for(const job of Object.keys(classes) as ClassId[])for(const skill of skills[job])for(let n=1;n<=5;n++){const ranked=skillAtRank(skill,n),lv=skill.level;expect(ranked.power).toBe((200+(lv/10-1)*20+(n-1)*10)/100);expect(ranked.maxTargets).toBe((lv<=30?4:lv<=60?5:lv<=90?6:7)+Math.floor((n-1)/2));expect(ranked.id).toBe(skill.id);expect(['hit','area','stun','slow','poison']).toContain(ranked.effect);expect(ranked.radius).toBeGreaterThan(0);expect(ranked.range).toBeGreaterThan(0);}
});
test('global points learn/upgrade/reject caps, class switches cannot mint, and reset refunds current class only',()=>{
 const s=fresh(30);expect(s.skillPoints).toBe(30);learn(s,'swordsman-1');for(let n=0;n<4;n++)expect(s.upgradeSkill('swordsman-1')).toBe(true);expect(s.skillPoints).toBe(25);expect(s.upgradeSkill('swordsman-1')).toBe(false);expect(s.upgradeSkill('mage-1')).toBe(false);s.setClass('mage');learn(s,'mage-1');expect(s.skillPoints).toBe(24);s.setClass('swordsman');expect(s.skillPoints).toBe(24);expect(s.resetSkills()).toBe(true);expect(s.skillPoints).toBe(29);expect(s.skillRank('mage-1')).toBe(1);expect(s.skillRank('swordsman-1')).toBe(0);s.setClass('mage');s.resetSkills();expect(s.skillPoints).toBe(30);expect(s.resetSkills()).toBe(true);expect(s.skillPoints).toBe(30);
});
test('existing choices migrate to rank1 without resetting assets, and malformed rank maps cannot exceed budget',()=>{
 const s=fresh(20);learn(s,'swordsman-b-2');s.save.gold=1234;const saved=structuredClone(s.save);delete (saved as any).skillRanks;saved.version=7;const migrated=new Simulation(()=>.5,saved,null);expect(migrated.save.skillChoices).toEqual(saved.skillChoices);expect(migrated.save.gold).toBe(1234);expect(migrated.save.items).toEqual(saved.items);expect(migrated.skillRank('swordsman-1')).toBe(1);expect(migrated.skillRank('swordsman-b-2')).toBe(1);expect(migrated.skillPoints).toBe(18);migrated.upgradeSkill('swordsman-b-2');const reloaded=new Simulation(()=>.5,structuredClone(migrated.save),null);expect(reloaded.skillRank('swordsman-b-2')).toBe(2);
 const forged=structuredClone(reloaded.save);forged.skillRanks={'swordsman-1':Infinity,'swordsman-b-2':900,'mage-1':5,'fake':100};const safe=new Simulation(()=>.5,forged,null);expect(safe.skillRank('fake')).toBe(0);expect(safe.skillRank('mage-1')).toBe(0);expect(Object.values(safe.save.skillRanks).every(n=>n>=1&&n<=5)).toBe(true);expect(safe.skillPoints).toBeGreaterThanOrEqual(0);
});
test('every skill directly hits at most ranked cap in radius/LOS/range, with stable primary priority',()=>{
 for(const job of Object.keys(classes) as ClassId[])for(const base of skills[job]){const s=fresh();s.setClass(job);learn(s,base.id);for(let n=0;n<4;n++)s.upgradeSkill(base.id);enemies(s);const hitIds:number[]=[],hitAmounts:number[]=[];s.hit=(m,amount)=>{hitIds.push(m.id);hitAmounts.push(amount);};expect(s.castSkill(base.id)).toBe(true);if(s.cast){expect(s.upgradeSkill(base.id)).toBe(false);s.tick(s.cast.remaining+.001,0,0);}expect(hitIds).toHaveLength(s.skillList.find(k=>k.id===base.id)!.maxTargets!);expect(hitIds[0]).toBe(0);expect(new Set(hitIds).size).toBe(hitIds.length);expect(hitAmounts.every(n=>n===s.damage*skillAtRank(base,5).power)).toBe(true);expect(s.guard.time).toBe(0);expect(s.fury.time).toBe(0);}
 const s=fresh();learn(s,'swordsman-1');enemies(s,5);s.monsters[1].x=20;s.monsters[2].x=3;s.direct=(x,z)=>x!==s.monsters[3].x||z!==s.monsters[3].z;const ids:number[]=[];s.hit=m=>{ids.push(m.id);};s.castSkill('swordsman-1');expect(ids).toEqual([0,4]);
});
class Store implements RealmStore {realm:Realm|null=null;revision=0;async read(){return this.realm?{realm:structuredClone(this.realm),revision:this.revision}:null;}async create(r:Realm){this.realm=structuredClone(r);}async commit(rev:number,r:Realm){if(rev!==this.revision)return false;this.realm=structuredClone(r);this.revision++;return true;}}
test('server owns upgrade budget and replayed ranks spend once; cast freezes rank and forged fields are ignored',async()=>{
 const store=new Store(),id={id:'ranker',name:'Ranker'};let snap=await transact(store,id,{connect:true},1000);store.realm!.players.ranker.actor.save.level=30;const send=async(type:string,args:unknown[])=>snap=await transact(store,id,{commands:[{id:`${snap.player.session.id}:${snap.player.session.sequence+1}`,type,args}]},1000);await send('chooseSkill',['swordsman-1']);const command={id:`${snap.player.session.id}:${snap.player.session.sequence+1}`,type:'upgradeSkill',args:['swordsman-1',5]};snap=await transact(store,id,{commands:[command],...{skillRanks:{'swordsman-1':5},skillPoints:999}} as any,1000);expect(snap.player.actor.save.skillRanks['swordsman-1']).toBe(2);snap=await transact(store,id,{commands:[command]},1000);expect(snap.player.actor.save.skillRanks['swordsman-1']).toBe(2);await send('upgradeSkill',['mage-1']);expect(snap.player.actor.save.skillRanks['mage-1']).toBeUndefined();await send('resetSkills',[]);expect(snap.player.actor.save.skillRanks).toEqual({});
});
test('rank is frozen during casting and converted support skills cannot heal or buff',()=>{
 const s=fresh(30);s.setClass('mage');learn(s,'mage-1');enemies(s);let amount=0;s.hit=(_m,n)=>{amount=n;};expect(s.castSkill('mage-1')).toBe(true);expect(s.cast).not.toBeNull();expect(s.upgradeSkill('mage-1')).toBe(false);expect(s.skillRank('mage-1')).toBe(1);s.tick(.36,0,0);expect(amount).toBe(s.damage*2);expect(s.upgradeSkill('mage-1')).toBe(true);expect(s.skillRank('mage-1')).toBe(2);
 for(const id of ['swordsman-3','swordsman-5','swordsman-6','mage-3','mage-5','mage-6','archer-3','archer-5','archer-6']){const sim=fresh();sim.setClass(id.split('-')[0] as ClassId);learn(sim,id);enemies(sim);sim.save.hp=20;let support=0,hits=0;sim.onSupport=()=>{support++;};sim.hit=()=>{hits++;};expect(sim.castSkill(id)).toBe(true);if(sim.cast)sim.tick(sim.cast.remaining+.001,0,0);expect(hits).toBeGreaterThan(0);expect(sim.save.hp).toBe(20);expect(sim.guard.time).toBe(0);expect(sim.fury.time).toBe(0);expect(support).toBe(0);}
});
