type InstallEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
let pendingInstall:InstallEvent|undefined;
let installed=false;
const standalone=()=>matchMedia('(display-mode: standalone)').matches||matchMedia('(display-mode: fullscreen)').matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone);
const ios=()=>/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
export const pwaControls=()=>`<div class="pwa-controls"><button type="button" data-pwa-install hidden>Install Mossvale</button><button type="button" data-pwa-fullscreen hidden>Enter fullscreen</button><p data-pwa-message role="status" aria-live="polite"></p></div>`;
function refresh(){document.querySelectorAll<HTMLButtonElement>('[data-pwa-install]').forEach(button=>{button.hidden=installed||standalone();button.textContent=ios()&&!pendingInstall?'Add to Home Screen':'Install Mossvale'});document.querySelectorAll<HTMLButtonElement>('[data-pwa-fullscreen]').forEach(button=>{button.hidden=!document.fullscreenEnabled;button.textContent=document.fullscreenElement?'Exit fullscreen':'Enter fullscreen';button.setAttribute('aria-pressed',String(Boolean(document.fullscreenElement)))});}
export function bindPwaControls(root:ParentNode=document){
 root.querySelectorAll<HTMLButtonElement>('[data-pwa-install]').forEach(button=>button.onclick=async()=>{const message=button.closest('.pwa-controls')!.querySelector<HTMLElement>('[data-pwa-message]')!;if(!pendingInstall){message.textContent=ios()?'In Safari, tap Share, then Add to Home Screen. Open Mossvale from your Home Screen.':'Open your browser menu and choose Install app or Add to Home Screen, if available.';return;}const event=pendingInstall;pendingInstall=undefined;button.disabled=true;try{await event.prompt();const choice=await event.userChoice;message.textContent=choice.outcome==='accepted'?'Installation requested. Open Mossvale from your app launcher.':'You can install later from your browser menu.'}catch{message.textContent='Use your browser menu to install Mossvale.'}finally{button.disabled=false;refresh()}});
 root.querySelectorAll<HTMLButtonElement>('[data-pwa-fullscreen]').forEach(button=>button.onclick=async()=>{const message=button.closest('.pwa-controls')!.querySelector<HTMLElement>('[data-pwa-message]')!;try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();message.textContent=''}catch{message.textContent='Fullscreen is unavailable here. You can keep playing in this window.'}refresh()});refresh();
}
export function initializePwa(){
 window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();pendingInstall=event as InstallEvent;refresh()});window.addEventListener('appinstalled',()=>{installed=true;pendingInstall=undefined;document.querySelectorAll<HTMLButtonElement>('[data-pwa-install]').forEach(button=>button.hidden=true)});document.addEventListener('fullscreenchange',refresh);matchMedia('(display-mode: standalone)').addEventListener('change',refresh);
 if(import.meta.env.PROD&&'serviceWorker' in navigator)window.addEventListener('load',()=>{void navigator.serviceWorker.register('/sw.js',{scope:'/',updateViaCache:'none'}).catch(()=>{/* Installation remains available without offline support. */})},{once:true});
}
