// Generated by tools/export-mesh-characters.mjs from exported GLB content.
export const MODEL_ASSET_REVISIONS:Record<string,string> = {
  "swordsman": "430758a8ca0ccd0e",
  "mage": "8e3fba7b1bbc3b7a",
  "archer": "6e48d19759a7c901"
};
