// Generated by tools/export-mesh-characters.mjs from exported GLB content.
export const MODEL_ASSET_REVISIONS:Record<string,string> = {
  "swordsman": "ac437871ad45f436",
  "mage": "ca5e47b8f756d19c",
  "archer": "5e9e50e87d006fca"
};
